// Generated by scripts/generate-api-contract.mjs. Do not edit by hand.

export type FieldError = {
  "field": string;
  "code": string;
  "message": string;
};

export type ErrorDetail = {
  "code": string;
  "message": string;
  "fields": Array<FieldError>;
};

export type ErrorEnvelope = {
  "error": ErrorDetail;
  "request_id": string;
};

export type Links = {
  "self": string;
};

export type PageLinks = {
  "self": string;
  "next": string | null;
};

export type PageMetadata = {
  "per_page": number;
  "next_cursor": string | null;
};

export type Service = {
  "service": "ezacto";
  "version": "v1";
};

export type ServiceEnvelope = {
  "data": Service;
  "links": Links;
};

export type TokenAuthentication = {
  "kind": "token";
  "token_id": number;
  "scopes": Array<"time_entries:read" | "time_entries:write" | "projects:read" | "projects:write" | "clients:read" | "clients:write" | "invoices:read" | "invoices:write" | "expenses:read" | "expenses:write" | "team:read" | "schedule:read" | "schedule:write" | "reports:read">;
};

export type SessionAuthentication = {
  "kind": "session";
};

export type Whoami = {
  "user_id": number;
  "profile": "member" | "project_manager" | "people_admin" | "accounting" | "executive_manager" | "administrator";
  "manager_grants": Array<string>;
  "authentication": TokenAuthentication | SessionAuthentication;
};

export type WhoamiEnvelope = {
  "data": Whoami;
  "links": Links;
};

export type GeneralResource = {
  "id": number;
  "created_at": string;
  "updated_at": string;
  [key: string]: unknown;
};

export type GeneralMutationInput = {
  [key: string]: unknown;
};

export type GeneralResourceEnvelope = {
  "data": GeneralResource;
  "links": Links;
};

export type GeneralResourcePage = {
  "data": Array<GeneralResource>;
  "links": PageLinks;
  "page": PageMetadata;
};

export type UserRate = {
  "id": number;
  "user_id": number;
  "amount_cents": number;
  "start_date": string | null;
  "end_date": string | null;
  "created_at": string;
  "updated_at": string;
};

export type UserRateInput = {
  "amount_cents": number;
  "start_date"?: string | null;
};

export type UserRateEnvelope = {
  "data": UserRate;
  "links": Links;
};

export type UserRatePage = {
  "data": Array<UserRate>;
  "links": PageLinks;
  "page": PageMetadata;
};

export type ApiToken = {
  "id": number;
  "name": string;
  "scopes": Array<"time_entries:read" | "time_entries:write" | "projects:read" | "projects:write" | "clients:read" | "clients:write" | "invoices:read" | "invoices:write" | "expenses:read" | "expenses:write" | "team:read" | "schedule:read" | "schedule:write" | "reports:read">;
  "token_hint": string;
  "created_at": string;
  "last_used_at": string | null;
  "expires_at": string | null;
  "revoked_at": string | null;
};

export type IssuedApiToken = (ApiToken) & ({
  "token": string;
});

export type CreateApiTokenInput = {
  "name": string;
  "scopes": Array<"time_entries:read" | "time_entries:write" | "projects:read" | "projects:write" | "clients:read" | "clients:write" | "invoices:read" | "invoices:write" | "expenses:read" | "expenses:write" | "team:read" | "schedule:read" | "schedule:write" | "reports:read">;
  "expires_at"?: string | null;
};

export type ApiTokenEnvelope = {
  "data": ApiToken;
  "links": Links;
};

export type IssuedApiTokenEnvelope = {
  "data": IssuedApiToken;
  "links": Links;
};

export type ApiTokenListEnvelope = {
  "data": Array<ApiToken>;
  "links": Links;
};

export type TimeEntry = {
  "id": number;
  "user_id": number;
  "project_id": number;
  "task_id": number;
  "user_assignment_id"?: number;
  "task_assignment_id"?: number;
  "spent_date": string;
  "seconds": number;
  "seconds_without_timer"?: number;
  "rounded_seconds"?: number;
  "is_running": boolean;
  "timer_started_at"?: string | null;
  "started_time"?: string | null;
  "ended_time"?: string | null;
  "notes"?: string | null;
  "billable": boolean;
  "budgeted": boolean;
  "approval_status": "unsubmitted" | "submitted" | "approved";
  "invoice_id"?: number | null;
  "is_billed": boolean;
  "is_locked": boolean;
  "locked_reason_code"?: string | null;
  "locked_reason"?: string | null;
  "external_ref"?: {
  [key: string]: unknown;
} | null;
  "calendar_event_ref"?: {
  [key: string]: unknown;
} | null;
  "billable_rate_cents"?: number | null;
  "cost_rate_cents"?: number | null;
  "created_at": string;
  "updated_at": string;
};

export type TimeEntryInput = {
  "project_id": number;
  "task_id": number;
  "spent_date"?: string;
  "seconds"?: number;
  "started_time"?: string;
  "ended_time"?: string;
  "notes"?: string | null;
  "budgeted"?: boolean;
  "external_ref"?: {
  [key: string]: unknown;
} | null;
  "calendar_event_ref"?: {
  [key: string]: unknown;
} | null;
};

export type TimeEntryPatch = {
  "project_id"?: number;
  "task_id"?: number;
  "spent_date"?: string;
  "seconds"?: number;
  "started_time"?: string;
  "ended_time"?: string;
  "notes"?: string | null;
  "budgeted"?: boolean;
  "external_ref"?: {
  [key: string]: unknown;
} | null;
  "calendar_event_ref"?: {
  [key: string]: unknown;
} | null;
};

export type TimeEntryEnvelope = {
  "data": TimeEntry;
  "links": Links;
};

export type TimeEntryPage = {
  "data": Array<TimeEntry>;
  "links": PageLinks;
  "page": PageMetadata;
};

export type Expense = {
  "id": number;
  "user_id": number;
  "project_id": number;
  "expense_category_id": number;
  "spent_date": string;
  "notes"?: string | null;
  "units"?: number | null;
  "total_cost_cents": number;
  "billable": boolean;
  "approval_status": "unsubmitted" | "submitted" | "approved";
  "invoice_id"?: number | null;
  "is_billed": boolean;
  "is_locked": boolean;
  "locked_reason_code"?: string | null;
  "locked_reason"?: string | null;
  "reimbursable": boolean;
  "reimbursement_status": "none" | "pending" | "approved" | "paid";
  "payout_ref"?: string | null;
  "created_at": string;
  "updated_at": string;
};

export type ExpenseInput = {
  "project_id": number;
  "expense_category_id": number;
  "spent_date": string;
  "notes"?: string | null;
  "units"?: number;
  "total_cost_cents"?: number;
  "billable"?: boolean;
  "reimbursable"?: boolean;
};

export type ExpensePatch = {
  "project_id"?: number;
  "expense_category_id"?: number;
  "spent_date"?: string;
  "notes"?: string | null;
  "units"?: number;
  "total_cost_cents"?: number;
  "billable"?: boolean;
  "reimbursable"?: boolean;
};

export type ExpenseEnvelope = {
  "data": Expense;
  "links": Links;
};

export type ExpensePage = {
  "data": Array<Expense>;
  "links": PageLinks;
  "page": PageMetadata;
};

export interface EzactoClientOptions {
  baseUrl: string;
  token?: string;
  fetch?: typeof globalThis.fetch;
  headers?: HeadersInit;
}

export class EzactoApiError extends Error {
  readonly status: number;
  readonly body: unknown;
  readonly requestId: string | null;

  constructor(status: number, body: unknown, requestId: string | null) {
    super(`ezacto API request failed with status ${status}`);
    this.name = "EzactoApiError";
    this.status = status;
    this.body = body;
    this.requestId = requestId;
  }
}

interface RequestOptions {
  query?: Readonly<Record<string, string | number | boolean | undefined>> | undefined;
  body?: unknown;
  signal?: AbortSignal | undefined;
  headers?: HeadersInit | undefined;
}

export class EzactoClient {
  private readonly baseUrl: string;
  private readonly token: string | undefined;
  private readonly fetchImplementation: typeof globalThis.fetch;
  private readonly defaultHeaders: Headers;

  constructor(options: EzactoClientOptions) {
    this.baseUrl = options.baseUrl.endsWith("/")
      ? options.baseUrl
      : `${options.baseUrl}/`;
    this.token = options.token;
    this.fetchImplementation = options.fetch ?? globalThis.fetch;
    this.defaultHeaders = new Headers(options.headers);
  }

  private async request<T>(
    method: string,
    path: string,
    options: RequestOptions,
  ): Promise<T> {
    const url = new URL(path.replace(/^\//, ""), this.baseUrl);
    for (const [name, value] of Object.entries(options.query ?? {})) {
      if (value !== undefined) url.searchParams.set(name, String(value));
    }
    const headers = new Headers(this.defaultHeaders);
    if (this.token !== undefined) headers.set("authorization", `Bearer ${this.token}`);
    if (options.body !== undefined) headers.set("content-type", "application/json");
    const response = await this.fetchImplementation(url, {
      method,
      headers,
      ...(options.signal === undefined ? {} : { signal: options.signal }),
      ...(options.body === undefined ? {} : { body: JSON.stringify(options.body) }),
    });
    const text = await response.text();
    let body: unknown = undefined;
    if (text.length > 0) {
      try {
        body = JSON.parse(text);
      } catch {
        body = text;
      }
    }
    if (!response.ok) {
      throw new EzactoApiError(
        response.status,
        body,
        response.headers.get("x-request-id"),
      );
    }
    return body as T;
  }

  async getApiRoot(args: { signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<ServiceEnvelope> {
    return this.request<ServiceEnvelope>("GET", "/api/v1", {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getWhoami(args: { signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<WhoamiEnvelope> {
    return this.request<WhoamiEnvelope>("GET", "/api/v1/whoami", {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listApiTokens(args: { signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<ApiTokenListEnvelope> {
    return this.request<ApiTokenListEnvelope>("GET", "/api/v1/api-tokens", {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createApiToken(args: { body: CreateApiTokenInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<IssuedApiTokenEnvelope> {
    return this.request<IssuedApiTokenEnvelope>("POST", "/api/v1/api-tokens", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async revokeApiToken(args: { "tokenId": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<ApiTokenEnvelope> {
    return this.request<ApiTokenEnvelope>("DELETE", "/api/v1/api-tokens/:tokenId".replace(":tokenId", encodeURIComponent(String(args["tokenId"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listClients(args: { query?: { "cursor"?: string; "per_page"?: number; "is_active"?: boolean; "updated_since"?: string; "parent_client_id"?: number; "bill_to_client_id"?: number }; signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<GeneralResourcePage> {
    return this.request<GeneralResourcePage>("GET", "/api/v1/clients", {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createClient(args: { body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("POST", "/api/v1/clients", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getClient(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("GET", "/api/v1/clients/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async updateClient(args: { "id": number; body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("PATCH", "/api/v1/clients/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async deleteClient(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<void> {
    return this.request<void>("DELETE", "/api/v1/clients/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listContacts(args: { query?: { "cursor"?: string; "per_page"?: number; "client_id"?: number; "updated_since"?: string }; signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<GeneralResourcePage> {
    return this.request<GeneralResourcePage>("GET", "/api/v1/contacts", {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createContact(args: { body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("POST", "/api/v1/contacts", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getContact(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("GET", "/api/v1/contacts/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async updateContact(args: { "id": number; body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("PATCH", "/api/v1/contacts/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async deleteContact(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<void> {
    return this.request<void>("DELETE", "/api/v1/contacts/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listProjects(args: { query?: { "cursor"?: string; "per_page"?: number; "client_id"?: number; "is_active"?: boolean; "updated_since"?: string }; signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<GeneralResourcePage> {
    return this.request<GeneralResourcePage>("GET", "/api/v1/projects", {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createProject(args: { body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("POST", "/api/v1/projects", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getProject(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("GET", "/api/v1/projects/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async updateProject(args: { "id": number; body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("PATCH", "/api/v1/projects/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async deleteProject(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<void> {
    return this.request<void>("DELETE", "/api/v1/projects/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listTasks(args: { query?: { "cursor"?: string; "per_page"?: number; "is_active"?: boolean; "updated_since"?: string }; signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<GeneralResourcePage> {
    return this.request<GeneralResourcePage>("GET", "/api/v1/tasks", {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createTask(args: { body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("POST", "/api/v1/tasks", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getTask(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("GET", "/api/v1/tasks/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async updateTask(args: { "id": number; body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("PATCH", "/api/v1/tasks/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async deleteTask(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<void> {
    return this.request<void>("DELETE", "/api/v1/tasks/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listTaskAssignments(args: { query?: { "cursor"?: string; "per_page"?: number; "project_id"?: number; "task_id"?: number; "is_active"?: boolean; "updated_since"?: string }; signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<GeneralResourcePage> {
    return this.request<GeneralResourcePage>("GET", "/api/v1/task-assignments", {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createTaskAssignment(args: { body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("POST", "/api/v1/task-assignments", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getTaskAssignment(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("GET", "/api/v1/task-assignments/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async updateTaskAssignment(args: { "id": number; body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("PATCH", "/api/v1/task-assignments/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async deleteTaskAssignment(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<void> {
    return this.request<void>("DELETE", "/api/v1/task-assignments/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listUserAssignments(args: { query?: { "cursor"?: string; "per_page"?: number; "project_id"?: number; "user_id"?: number; "is_active"?: boolean; "updated_since"?: string }; signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<GeneralResourcePage> {
    return this.request<GeneralResourcePage>("GET", "/api/v1/user-assignments", {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createUserAssignment(args: { body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("POST", "/api/v1/user-assignments", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getUserAssignment(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("GET", "/api/v1/user-assignments/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async updateUserAssignment(args: { "id": number; body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("PATCH", "/api/v1/user-assignments/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async deleteUserAssignment(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<void> {
    return this.request<void>("DELETE", "/api/v1/user-assignments/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listUsers(args: { query?: { "cursor"?: string; "per_page"?: number; "is_active"?: boolean; "updated_since"?: string; "profile"?: "member" | "project_manager" | "people_admin" | "accounting" | "executive_manager" | "administrator"; "is_contractor"?: boolean }; signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<GeneralResourcePage> {
    return this.request<GeneralResourcePage>("GET", "/api/v1/users", {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createUser(args: { body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("POST", "/api/v1/users", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getUser(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("GET", "/api/v1/users/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async updateUser(args: { "id": number; body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("PATCH", "/api/v1/users/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async deleteUser(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<void> {
    return this.request<void>("DELETE", "/api/v1/users/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listRoles(args: { query?: { "cursor"?: string; "per_page"?: number }; signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<GeneralResourcePage> {
    return this.request<GeneralResourcePage>("GET", "/api/v1/roles", {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createRole(args: { body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("POST", "/api/v1/roles", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getRole(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("GET", "/api/v1/roles/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async updateRole(args: { "id": number; body: GeneralMutationInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<GeneralResourceEnvelope> {
    return this.request<GeneralResourceEnvelope>("PATCH", "/api/v1/roles/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async deleteRole(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<void> {
    return this.request<void>("DELETE", "/api/v1/roles/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listBillableRates(args: { "userId": number; query?: { "cursor"?: string; "per_page"?: number }; signal?: AbortSignal; headers?: HeadersInit }): Promise<UserRatePage> {
    return this.request<UserRatePage>("GET", "/api/v1/users/:userId/billable-rates".replace(":userId", encodeURIComponent(String(args["userId"]))), {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async appendBillableRate(args: { "userId": number; body: UserRateInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<UserRateEnvelope> {
    return this.request<UserRateEnvelope>("POST", "/api/v1/users/:userId/billable-rates".replace(":userId", encodeURIComponent(String(args["userId"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getBillableRate(args: { "userId": number; "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<UserRateEnvelope> {
    return this.request<UserRateEnvelope>("GET", "/api/v1/users/:userId/billable-rates/:id".replace(":userId", encodeURIComponent(String(args["userId"]))).replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listCostRates(args: { "userId": number; query?: { "cursor"?: string; "per_page"?: number }; signal?: AbortSignal; headers?: HeadersInit }): Promise<UserRatePage> {
    return this.request<UserRatePage>("GET", "/api/v1/users/:userId/cost-rates".replace(":userId", encodeURIComponent(String(args["userId"]))), {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async appendCostRate(args: { "userId": number; body: UserRateInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<UserRateEnvelope> {
    return this.request<UserRateEnvelope>("POST", "/api/v1/users/:userId/cost-rates".replace(":userId", encodeURIComponent(String(args["userId"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getCostRate(args: { "userId": number; "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<UserRateEnvelope> {
    return this.request<UserRateEnvelope>("GET", "/api/v1/users/:userId/cost-rates/:id".replace(":userId", encodeURIComponent(String(args["userId"]))).replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listTimeEntries(args: { query?: { "cursor"?: string; "per_page"?: number; "user_id"?: number; "client_id"?: number; "project_id"?: number; "spent_date"?: string; "from"?: string; "to"?: string; "approval_status"?: "unsubmitted" | "submitted" | "approved"; "invoice_id"?: number; "is_billed"?: boolean; "billable"?: boolean; "updated_since"?: string; "task_id"?: number; "is_running"?: boolean; "budgeted"?: boolean; "external_reference_id"?: string }; signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<TimeEntryPage> {
    return this.request<TimeEntryPage>("GET", "/api/v1/time-entries", {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createTimeEntry(args: { body: TimeEntryInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<TimeEntryEnvelope> {
    return this.request<TimeEntryEnvelope>("POST", "/api/v1/time-entries", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getTimeEntry(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<TimeEntryEnvelope> {
    return this.request<TimeEntryEnvelope>("GET", "/api/v1/time-entries/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async updateTimeEntry(args: { "id": number; body: TimeEntryPatch; signal?: AbortSignal; headers?: HeadersInit }): Promise<TimeEntryEnvelope> {
    return this.request<TimeEntryEnvelope>("PATCH", "/api/v1/time-entries/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async deleteTimeEntry(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<TimeEntryEnvelope> {
    return this.request<TimeEntryEnvelope>("DELETE", "/api/v1/time-entries/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async stopTimeEntry(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<TimeEntryEnvelope> {
    return this.request<TimeEntryEnvelope>("POST", "/api/v1/time-entries/:id/stop".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async restartTimeEntry(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<TimeEntryEnvelope> {
    return this.request<TimeEntryEnvelope>("POST", "/api/v1/time-entries/:id/restart".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async listExpenses(args: { query?: { "cursor"?: string; "per_page"?: number; "user_id"?: number; "client_id"?: number; "project_id"?: number; "spent_date"?: string; "from"?: string; "to"?: string; "approval_status"?: "unsubmitted" | "submitted" | "approved"; "invoice_id"?: number; "is_billed"?: boolean; "billable"?: boolean; "updated_since"?: string; "expense_category_id"?: number; "reimbursable"?: boolean; "reimbursement_status"?: "none" | "pending" | "approved" | "paid" }; signal?: AbortSignal; headers?: HeadersInit } = {}): Promise<ExpensePage> {
    return this.request<ExpensePage>("GET", "/api/v1/expenses", {
      query: args.query,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async createExpense(args: { body: ExpenseInput; signal?: AbortSignal; headers?: HeadersInit }): Promise<ExpenseEnvelope> {
    return this.request<ExpenseEnvelope>("POST", "/api/v1/expenses", {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async getExpense(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<ExpenseEnvelope> {
    return this.request<ExpenseEnvelope>("GET", "/api/v1/expenses/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }

  async updateExpense(args: { "id": number; body: ExpensePatch; signal?: AbortSignal; headers?: HeadersInit }): Promise<ExpenseEnvelope> {
    return this.request<ExpenseEnvelope>("PATCH", "/api/v1/expenses/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      body: args.body,
      signal: args.signal,
      headers: args.headers,
    });
  }

  async deleteExpense(args: { "id": number; signal?: AbortSignal; headers?: HeadersInit }): Promise<ExpenseEnvelope> {
    return this.request<ExpenseEnvelope>("DELETE", "/api/v1/expenses/:id".replace(":id", encodeURIComponent(String(args["id"]))), {
      signal: args.signal,
      headers: args.headers,
    });
  }
}
