import { readFile, readdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it, vi } from 'vitest'
import {
  cssCustomProperty,
  defaultTheme,
  loadActiveThemeFonts,
  slot,
  themeFontNames,
  themeManifest,
  themeSlotNames,
} from '../src/index.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const filesUnder = async (directory: string): Promise<string[]> => {
  const entries = await readdir(directory, { withFileTypes: true })
  const paths = await Promise.all(
    entries.map((entry) => {
      const path = resolve(directory, entry.name)
      return entry.isDirectory() ? filesUnder(path) : Promise.resolve([path])
    }),
  )
  return paths.flat()
}

describe('D16 theme token contract', () => {
  it('[unit] snapshot-compiles the precision theme to semantic CSS properties', async () => {
    const css = await readFile(resolve(root, 'generated', 'themes.css'), 'utf8')
    expect(css).toMatchInlineSnapshot(`
      "/* Generated by scripts/compile-theme-tokens.mjs. Do not edit. */
      :root, [data-ez-theme="precision"] {
        --ez-ground: #FFFFFF;
        --ez-surface: #F5F6F7;
        --ez-border: #E3E5E8;
        --ez-ink: #14161A;
        --ez-muted: #676C74;
        --ez-action: #16794A;
        --ez-action-fg: #FFFFFF;
        --ez-live: #E8590C;
        --ez-data: #2F5AE0;
        --ez-money: #FDF7EE;
        --ez-status-bg: #EDF1F5;
        --ez-status-fg: #676C74;
        --ez-ink-2: #3A3D42;
        --ez-orange-tint: #FDEDE3;
        --ez-blue-light: #A8BCF5;
        --ez-red: #C92A2A;
        --ez-amber: #F1B34A;
        --ez-amber-bg: #FEF6E4;
        --ez-live-text: #BA470A;
        --ez-surface-2: #EBEDEF;
        --ez-row-hover: #E1ECFB;
        --ez-font-display: "IBM Plex Sans";
        --ez-font-body: "IBM Plex Sans";
        --ez-font-mono: "IBM Plex Mono";
        --ez-radius: 6px;
      }
      "
    `)
    expect(defaultTheme).toBe('precision')
    expect(Object.keys(themeManifest)).toEqual(['precision'])
    expect(Object.keys(themeManifest.precision.colors)).toEqual([...themeSlotNames])
    expect(Object.keys(themeManifest.precision.fonts)).toEqual([...themeFontNames])
    expect(themeSlotNames.map(cssCustomProperty)).toContain('--ez-action-fg')
    expect(slot('live')).toBe('var(--ez-live)')
  })

  it('[unit] carries the nested surface and the row-hover tint as contract slots', () => {
    // Neither value can be re-derived from the rest of the palette by reading
    // it, so both are pinned here against the decisions recorded on #292.
    //
    // `surface_2` is a panel inside a card -- a toolbar inside a workspace, a
    // summary band inside a list. It is `surface`'s own step off `ground`
    // taken a second time, the same neutral at the same distance, so nesting
    // reads as one more rung of one ramp rather than as a second colour.
    const channels = (from: string, to: string): number[] =>
      [1, 3, 5].map(
        (index) =>
          Number.parseInt(from.slice(index, index + 2), 16) -
          Number.parseInt(to.slice(index, index + 2), 16),
      )
    const { ground, surface, surface_2: nested, row_hover: rowHover } =
      themeManifest.precision.colors
    expect(channels(ground, surface)).toEqual([10, 9, 8])
    expect(channels(ground, nested)).toEqual([20, 18, 16])

    // `row_hover` is read from the legacy Harvest roster, where the hovered row
    // samples uniformly at rgb(225, 236, 251) against #FFFFFF unhovered --
    // hsl(215, 76%, 93%), a high-lightness tint of the billable blue. The
    // screenshot is not in this repository, only the value.
    expect(rowHover).toBe('#E1ECFB')

    expect(themeSlotNames).toContain('surface_2')
    expect(themeSlotNames).toContain('row_hover')
    expect(cssCustomProperty('surface_2')).toBe('--ez-surface-2')
    expect(cssCustomProperty('row_hover')).toBe('--ez-row-hover')
  })

  it('[unit] requests only the active theme font stylesheet', async () => {
    const request = vi.fn<(href: string) => Promise<void>>().mockResolvedValue(undefined)
    await loadActiveThemeFonts('precision', request)
    expect(request).toHaveBeenCalledTimes(1)
    expect(request).toHaveBeenCalledWith(
      'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600;700&display=swap',
    )
    expect(request.mock.calls.flat().join(' ')).not.toMatch(/Space|Roboto|Unica/u)
  })

  it('[unit] rejects literal colors from component and shell source', async () => {
    const sourceFiles = (
      await Promise.all([
        filesUnder(resolve(root, 'src', 'components')),
        filesUnder(resolve(root, 'src', 'shell')),
        filesUnder(resolve(root, 'src', 'week-grid')),
      ])
    )
      .flat()
      .filter((path) => path.endsWith('.ts') || path.endsWith('.tsx') || path.endsWith('.css'))
    expect(sourceFiles.length).toBeGreaterThan(0)
    for (const path of sourceFiles) {
      const source = await readFile(path, 'utf8')
      expect(source, path).not.toMatch(/#[0-9a-fA-F]{3,8}\b/u)
    }
  })

  it('[unit] spends every token it declares, or names why not', async () => {
    // A design-system slot that nothing references is not a token, it is a
    // decision nobody applied -- `surface_2` and `row_hover` both sat in the
    // contract and in the contrast gate while the stylesheet used neither, so
    // the grouped-table band and the row hover stayed the wrong colour and
    // every gate still passed.
    //
    // These five are the same shape and are not guessed at here: a slot's
    // purpose is a decision, and inventing one is how a token comes to mean two
    // things. The list is a ratchet -- it may shrink, and a new name appearing
    // in it is a token that shipped without a job.
    const awaitingAPurpose = ['money', 'ink_2', 'blue_light', 'amber', 'amber_bg']
    const stylesheet = await readFile(resolve(root, 'src', 'shell', 'shell.css'), 'utf8')
    const unspent = themeSlotNames.filter(
      (name) => !stylesheet.includes(`var(${cssCustomProperty(name)})`),
    )
    expect(unspent).toEqual(awaitingAPurpose)
  })

  it('[unit] gives every page surface exactly one measure', async () => {
    // `page--grid` and `page--document` replaced nine hand-written max-width
    // caps, and were then applied to nothing -- so settings forms ran the full
    // width of the monitor. Every page container declares which surface it is.
    const renderers = (await filesUnder(resolve(root, 'src')))
      .filter((path) => path.endsWith('render.ts') && !path.includes('generated'))
    const containers: string[] = []
    for (const path of renderers) {
      const source = await readFile(path, 'utf8')
      for (const [, classes] of source.matchAll(/<main class="(app-content[^"]*)"/gu)) {
        containers.push(`${path}: ${classes}`)
      }
    }
    expect(containers.length).toBeGreaterThan(0)
    for (const container of containers) {
      const grid = container.includes('page--grid')
      const document = container.includes('page--document')
      expect(grid !== document, container).toBe(true)
    }
  })

  it('[unit] gives navigation a hover state, not only a current state', async () => {
    // A tab that says which one you are on and nothing about which one you are
    // about to choose reads as a label rather than a control.
    const stylesheet = await readFile(resolve(root, 'src', 'shell', 'shell.css'), 'utf8')
    expect(stylesheet).toMatch(/\.tabstrip a:hover/u)
    expect(stylesheet).toMatch(/\.tabstrip\.view-switch a:hover/u)
  })
})
