import { readFile, readdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it, vi } from 'vitest'
import {
  cssCustomProperty,
  defaultTheme,
  loadActiveThemeFonts,
  slot,
  themeFontNames,
  themeManifest,
  themeSlotNames,
} from '../src/index.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const filesUnder = async (directory: string): Promise<string[]> => {
  const entries = await readdir(directory, { withFileTypes: true })
  const paths = await Promise.all(
    entries.map((entry) => {
      const path = resolve(directory, entry.name)
      return entry.isDirectory() ? filesUnder(path) : Promise.resolve([path])
    }),
  )
  return paths.flat()
}

describe('D16 theme token contract', () => {
  it('[unit] snapshot-compiles the precision theme to semantic CSS properties', async () => {
    const css = await readFile(resolve(root, 'generated', 'themes.css'), 'utf8')
    expect(css).toMatchInlineSnapshot(`
      "/* Generated by scripts/compile-theme-tokens.mjs. Do not edit. */
      :root, [data-ez-theme="precision"] {
        --ez-ground: #FFFFFF;
        --ez-surface: #F5F6F7;
        --ez-border: #E3E5E8;
        --ez-ink: #14161A;
        --ez-muted: #676C74;
        --ez-action: #16794A;
        --ez-action-fg: #FFFFFF;
        --ez-live: #E8590C;
        --ez-data: #2F5AE0;
        --ez-money: #FDF7EE;
        --ez-status-bg: #EDF1F5;
        --ez-status-fg: #676C74;
        --ez-ink-2: #3A3D42;
        --ez-orange-tint: #FDEDE3;
        --ez-blue-light: #A8BCF5;
        --ez-red: #C92A2A;
        --ez-amber: #F1B34A;
        --ez-amber-bg: #FEF6E4;
        --ez-font-display: "IBM Plex Sans";
        --ez-font-body: "IBM Plex Sans";
        --ez-font-mono: "IBM Plex Mono";
        --ez-radius: 6px;
      }
      "
    `)
    expect(defaultTheme).toBe('precision')
    expect(Object.keys(themeManifest)).toEqual(['precision'])
    expect(Object.keys(themeManifest.precision.colors)).toEqual([...themeSlotNames])
    expect(Object.keys(themeManifest.precision.fonts)).toEqual([...themeFontNames])
    expect(themeSlotNames.map(cssCustomProperty)).toContain('--ez-action-fg')
    expect(slot('live')).toBe('var(--ez-live)')
  })

  it('[unit] requests only the active theme font stylesheet', async () => {
    const request = vi.fn<(href: string) => Promise<void>>().mockResolvedValue(undefined)
    await loadActiveThemeFonts('precision', request)
    expect(request).toHaveBeenCalledTimes(1)
    expect(request).toHaveBeenCalledWith(
      'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600;700&display=swap',
    )
    expect(request.mock.calls.flat().join(' ')).not.toMatch(/Space|Roboto|Unica/u)
  })

  it('[unit] rejects literal colors from component and shell source', async () => {
    const sourceFiles = (
      await Promise.all([
        filesUnder(resolve(root, 'src', 'components')),
        filesUnder(resolve(root, 'src', 'shell')),
        filesUnder(resolve(root, 'src', 'week-grid')),
      ])
    )
      .flat()
      .filter((path) => path.endsWith('.ts') || path.endsWith('.tsx') || path.endsWith('.css'))
    expect(sourceFiles.length).toBeGreaterThan(0)
    for (const path of sourceFiles) {
      const source = await readFile(path, 'utf8')
      expect(source, path).not.toMatch(/#[0-9a-fA-F]{3,8}\b/u)
    }
  })
})
