import {
  attachmentContractOperations,
  attachmentContractSchemas,
} from './attachment-contract.js'

export type ApiContractMethod = "get" | "post" | "patch" | "delete";

export interface ApiContractParameter {
  name: string;
  location: "path" | "query" | "header";
  schema: Readonly<Record<string, unknown>>;
  required?: boolean;
}

export interface ApiContractOperation {
  method: ApiContractMethod;
  /** Runtime/Hono path. OpenAPI braces are produced by the generator. */
  path: string;
  operationId: string;
  summary: string;
  tag: string;
  responseStatus: number;
  responseSchema?: string;
  requestSchema?: string;
  requestRequired?: boolean;
  requestContentType?: "application/json" | "multipart/form-data";
  binaryResponse?: boolean;
  sessionOnly?: boolean;
  public?: boolean;
  parameters?: readonly ApiContractParameter[];
  generateClient?: boolean;
}

type JsonSchema = Readonly<Record<string, unknown>>;

const stringSchema = { type: "string" } as const;
const integerSchema = { type: "integer", minimum: 1 } as const;
const booleanSchema = { type: "boolean" } as const;
const dateSchema = { type: "string", format: "date" } as const;
const timestampSchema = { type: "string", format: "date-time" } as const;

const query = (
  name: string,
  schema: JsonSchema = stringSchema,
): ApiContractParameter => ({ name, location: "query", schema });

const path = (name: string): ApiContractParameter => ({
  name,
  location: "path",
  schema: integerSchema,
  required: true,
});

const stringPath = (name: string): ApiContractParameter => ({
  name,
  location: "path",
  schema: stringSchema,
  required: true,
});

const header = (name: string): ApiContractParameter => ({
  name,
  location: "header",
  schema: stringSchema,
  required: true,
});

const pageParameters = [
  query("cursor"),
  query("per_page", { type: "integer", minimum: 1, maximum: 200 }),
] as const;

const filterSchemas: Readonly<Record<string, JsonSchema>> = {
  is_active: booleanSchema,
  updated_since: timestampSchema,
  client_id: integerSchema,
  project_id: integerSchema,
  task_id: integerSchema,
  user_id: integerSchema,
  parent_client_id: integerSchema,
  bill_to_client_id: integerSchema,
  profile: {
    type: "string",
    enum: [
      "member",
      "project_manager",
      "people_admin",
      "accounting",
      "executive_manager",
      "administrator",
    ],
  },
  is_contractor: booleanSchema,
};

const generalResources = [
  {
    plural: "clients",
    singular: "Client",
    filters: [
      "is_active",
      "updated_since",
      "parent_client_id",
      "bill_to_client_id",
    ],
  },
  {
    plural: "contacts",
    singular: "Contact",
    filters: ["client_id", "updated_since"],
  },
  {
    plural: "projects",
    singular: "Project",
    filters: ["client_id", "is_active", "updated_since"],
  },
  {
    plural: "tasks",
    singular: "Task",
    filters: ["is_active", "updated_since"],
  },
  {
    plural: "task-assignments",
    singular: "TaskAssignment",
    filters: ["project_id", "task_id", "is_active", "updated_since"],
  },
  {
    plural: "user-assignments",
    singular: "UserAssignment",
    filters: ["project_id", "user_id", "is_active", "updated_since"],
    sessionOnlyMutation: true,
  },
  {
    plural: "users",
    singular: "User",
    filters: ["is_active", "updated_since", "profile", "is_contractor"],
    sessionOnlyMutation: true,
  },
  {
    plural: "roles",
    singular: "Role",
    filters: [],
    sessionOnlyMutation: true,
  },
] as const;

const generalOperations = (): ApiContractOperation[] =>
  generalResources.flatMap((resource) => {
    const collection = `/api/v1/${resource.plural}`;
    const member = `${collection}/:id`;
    const listParameters = [
      ...pageParameters,
      ...resource.filters.map((name) => query(name, filterSchemas[name]!)),
    ];
    return [
      {
        method: "get",
        path: collection,
        operationId: `list${resource.singular}s`,
        summary: `List ${resource.plural}`,
        tag: resource.plural,
        responseStatus: 200,
        responseSchema: "GeneralResourcePage",
        parameters: listParameters,
      },
      {
        method: "post",
        path: collection,
        operationId: `create${resource.singular}`,
        summary: `Create a ${resource.singular.toLowerCase()}`,
        tag: resource.plural,
        responseStatus: 201,
        responseSchema: "GeneralResourceEnvelope",
        requestSchema: "GeneralMutationInput",
        requestRequired: true,
        ...("sessionOnlyMutation" in resource &&
        resource.sessionOnlyMutation === true
          ? { sessionOnly: true }
          : {}),
      },
      {
        method: "get",
        path: member,
        operationId: `get${resource.singular}`,
        summary: `Get a ${resource.singular.toLowerCase()}`,
        tag: resource.plural,
        responseStatus: 200,
        responseSchema: "GeneralResourceEnvelope",
        parameters: [path("id")],
      },
      {
        method: "patch",
        path: member,
        operationId: `update${resource.singular}`,
        summary: `Update a ${resource.singular.toLowerCase()}`,
        tag: resource.plural,
        responseStatus: 200,
        responseSchema: "GeneralResourceEnvelope",
        requestSchema: "GeneralMutationInput",
        requestRequired: true,
        parameters: [path("id")],
        ...("sessionOnlyMutation" in resource &&
        resource.sessionOnlyMutation === true
          ? { sessionOnly: true }
          : {}),
      },
      {
        method: "delete",
        path: member,
        operationId: `delete${resource.singular}`,
        summary: `Delete or archive a ${resource.singular.toLowerCase()}`,
        tag: resource.plural,
        responseStatus: 204,
        parameters: [path("id")],
        ...("sessionOnlyMutation" in resource &&
        resource.sessionOnlyMutation === true
          ? { sessionOnly: true }
          : {}),
      },
    ];
  });

const rateOperations = (): ApiContractOperation[] =>
  (["billable", "cost"] as const).flatMap((kind) => {
    const title = kind === "billable" ? "BillableRate" : "CostRate";
    const collection = `/api/v1/users/:userId/${kind}-rates`;
    const member = `${collection}/:id`;
    const tag = "user-rates";
    const identifiers = [path("userId")];
    const memberIdentifiers = [path("userId"), path("id")];
    const rejected = (method: "patch" | "delete", route: string) =>
      ({
        method,
        path: route,
        operationId: `${method}${title}${route === collection ? "Collection" : ""}NotAllowed`,
        summary: `${title} records are append-only`,
        tag,
        responseStatus: 405,
        responseSchema: "ErrorEnvelope",
        parameters: route === collection ? identifiers : memberIdentifiers,
        generateClient: false,
      }) satisfies ApiContractOperation;
    return [
      {
        method: "get",
        path: collection,
        operationId: `list${title}s`,
        summary: `List ${kind} rates for a user`,
        tag,
        responseStatus: 200,
        responseSchema: "UserRatePage",
        parameters: [...identifiers, ...pageParameters],
      },
      {
        method: "post",
        path: collection,
        operationId: `append${title}`,
        summary: `Append a ${kind} rate for a user`,
        tag,
        responseStatus: 201,
        responseSchema: "UserRateEnvelope",
        requestSchema: "UserRateInput",
        requestRequired: true,
        sessionOnly: true,
        parameters: identifiers,
      },
      {
        method: "get",
        path: member,
        operationId: `get${title}`,
        summary: `Get a ${kind} rate`,
        tag,
        responseStatus: 200,
        responseSchema: "UserRateEnvelope",
        parameters: memberIdentifiers,
      },
      rejected("patch", member),
      rejected("delete", member),
      rejected("patch", collection),
      rejected("delete", collection),
    ];
  });

const trackedListParameters = [
  ...pageParameters,
  query("user_id", integerSchema),
  query("client_id", integerSchema),
  query("project_id", integerSchema),
  query("spent_date", dateSchema),
  query("from", dateSchema),
  query("to", dateSchema),
  query("approval_status", {
    type: "string",
    enum: ["unsubmitted", "submitted", "approved"],
  }),
  query("invoice_id", integerSchema),
  query("is_billed", booleanSchema),
  query("billable", booleanSchema),
  query("updated_since", timestampSchema),
] as const;

const timeEntryOperations: ApiContractOperation[] = [
  {
    method: "get",
    path: "/api/v1/time-entries",
    operationId: "listTimeEntries",
    summary: "List the acting user's time entries",
    tag: "time-entries",
    responseStatus: 200,
    responseSchema: "TimeEntryPage",
    parameters: [
      ...trackedListParameters,
      query("task_id", integerSchema),
      query("is_running", booleanSchema),
      query("budgeted", booleanSchema),
      query("external_reference_id"),
    ],
  },
  {
    method: "post",
    path: "/api/v1/time-entries",
    operationId: "createTimeEntry",
    summary: "Create or start a time entry",
    tag: "time-entries",
    responseStatus: 201,
    responseSchema: "TimeEntryEnvelope",
    requestSchema: "TimeEntryInput",
    requestRequired: true,
  },
  ...(["get", "patch", "delete"] as const).map((method) => ({
    method,
    path: "/api/v1/time-entries/:id",
    operationId: `${method === "get" ? "get" : method === "patch" ? "update" : "delete"}TimeEntry`,
    summary: `${method === "get" ? "Get" : method === "patch" ? "Update" : "Delete"} a time entry`,
    tag: "time-entries",
    responseStatus: 200,
    responseSchema: "TimeEntryEnvelope",
    ...(method === "patch"
      ? { requestSchema: "TimeEntryPatch", requestRequired: true }
      : {}),
    parameters: [path("id")],
  })),
  ...(["stop", "restart"] as const).map((action) => ({
    method: "post" as const,
    path: `/api/v1/time-entries/:id/${action}`,
    operationId: `${action}TimeEntry`,
    summary: `${action === "stop" ? "Stop" : "Restart"} a time entry`,
    tag: "time-entries",
    responseStatus: 200,
    responseSchema: "TimeEntryEnvelope",
    parameters: [path("id")],
  })),
];

const expenseOperations: ApiContractOperation[] = [
  {
    method: "get",
    path: "/api/v1/expenses",
    operationId: "listExpenses",
    summary: "List the acting user's expenses",
    tag: "expenses",
    responseStatus: 200,
    responseSchema: "ExpensePage",
    parameters: [
      ...trackedListParameters,
      query("expense_category_id", integerSchema),
      query("reimbursable", booleanSchema),
      query("reimbursement_status", {
        type: "string",
        enum: ["none", "pending", "approved", "paid"],
      }),
    ],
  },
  {
    method: "post",
    path: "/api/v1/expenses",
    operationId: "createExpense",
    summary: "Create an expense",
    tag: "expenses",
    responseStatus: 201,
    responseSchema: "ExpenseEnvelope",
    requestSchema: "ExpenseInput",
    requestRequired: true,
  },
  ...(["get", "patch", "delete"] as const).map((method) => ({
    method,
    path: "/api/v1/expenses/:id",
    operationId: `${method === "get" ? "get" : method === "patch" ? "update" : "delete"}Expense`,
    summary: `${method === "get" ? "Get" : method === "patch" ? "Update" : "Delete"} an expense`,
    tag: "expenses",
    responseStatus: 200,
    responseSchema: "ExpenseEnvelope",
    ...(method === "patch"
      ? { requestSchema: "ExpensePatch", requestRequired: true }
      : {}),
    parameters: [path("id")],
  })),
];

const idempotency = header("Idempotency-Key");

const moneyOperations: ApiContractOperation[] = [
  {
    method: "get",
    path: "/api/v1/invoices",
    operationId: "listInvoices",
    summary: "List invoices",
    tag: "invoices",
    responseStatus: 200,
    responseSchema: "InvoicePage",
    parameters: pageParameters,
  },
  {
    method: "get",
    path: "/api/v1/invoices/:id",
    operationId: "getInvoice",
    summary: "Get an invoice",
    tag: "invoices",
    responseStatus: 200,
    responseSchema: "InvoiceEnvelope",
    parameters: [path("id")],
  },
  {
    method: "get",
    path: "/api/v1/estimates",
    operationId: "listEstimates",
    summary: "List estimates",
    tag: "estimates",
    responseStatus: 200,
    responseSchema: "EstimatePage",
    parameters: pageParameters,
  },
  {
    method: "get",
    path: "/api/v1/estimates/:id",
    operationId: "getEstimate",
    summary: "Get an estimate",
    tag: "estimates",
    responseStatus: 200,
    responseSchema: "EstimateEnvelope",
    parameters: [path("id")],
  },
  {
    method: "get",
    path: "/api/v1/estimates/:id/messages",
    operationId: "listEstimateMessages",
    summary: "List estimate lifecycle messages",
    tag: "estimate-messages",
    responseStatus: 200,
    responseSchema: "EstimateMessageListEnvelope",
    parameters: [path("id")],
  },
  {
    method: "post",
    path: "/api/v1/estimates/:id/messages",
    operationId: "createEstimateMessage",
    summary: "Create a retry-safe estimate lifecycle message",
    tag: "estimate-messages",
    responseStatus: 201,
    responseSchema: "EstimateMessageCommandEnvelope",
    requestSchema: "EstimateMessageInput",
    requestRequired: true,
    parameters: [path("id"), idempotency],
  },
  {
    method: "post",
    path: "/api/v1/estimates/:id/convert",
    operationId: "convertEstimate",
    summary: "Convert an accepted estimate into one draft invoice",
    tag: "estimates",
    responseStatus: 201,
    responseSchema: "EstimateConversionEnvelope",
    requestSchema: "EstimateConversionInput",
    requestRequired: true,
    parameters: [path("id"), idempotency],
  },
  {
    method: "post",
    path: "/api/v1/invoice-generations",
    operationId: "generateInvoice",
    summary: "Delegate transactional tracked-resource invoice generation",
    tag: "invoices",
    responseStatus: 201,
    responseSchema: "InvoiceEnvelope",
    requestSchema: "InvoiceGenerationInput",
    requestRequired: true,
    parameters: [idempotency],
  },
  {
    method: "patch",
    path: "/api/v1/invoices/:id",
    operationId: "updateInvoice",
    summary: "Apply one retry-safe invoice edit",
    tag: "invoices",
    responseStatus: 200,
    responseSchema: "InvoiceCommandEnvelope",
    requestSchema: "InvoiceEditInput",
    requestRequired: true,
    parameters: [path("id"), idempotency],
  },
  {
    method: "post",
    path: "/api/v1/invoices/:id/line-items",
    operationId: "createInvoiceLine",
    summary: "Add a parent-owned invoice line",
    tag: "invoices",
    responseStatus: 201,
    responseSchema: "InvoiceCommandEnvelope",
    requestSchema: "InvoiceLineInput",
    requestRequired: true,
    parameters: [path("id"), idempotency],
  },
  ...(["patch", "delete"] as const).map((method) => ({
    method,
    path: "/api/v1/invoices/:id/line-items/:lineId",
    operationId: `${method === "patch" ? "update" : "delete"}InvoiceLine`,
    summary: `${method === "patch" ? "Update" : "Delete"} a parent-owned invoice line`,
    tag: "invoices",
    responseStatus: 200,
    responseSchema: "InvoiceCommandEnvelope",
    requestSchema:
      method === "patch" ? "InvoiceLineUpdateInput" : "VersionedRowDeleteInput",
    requestRequired: true,
    parameters: [path("id"), path("lineId"), idempotency],
  })),
  {
    method: "get",
    path: "/api/v1/invoices/:id/messages",
    operationId: "listInvoiceMessages",
    summary: "List invoice lifecycle messages",
    tag: "invoice-messages",
    responseStatus: 200,
    responseSchema: "InvoiceMessageListEnvelope",
    parameters: [path("id")],
  },
  {
    method: "post",
    path: "/api/v1/invoices/:id/messages",
    operationId: "createInvoiceMessage",
    summary: "Create an invoice lifecycle message",
    tag: "invoice-messages",
    responseStatus: 201,
    responseSchema: "InvoiceCommandEnvelope",
    requestSchema: "InvoiceMessageInput",
    requestRequired: true,
    parameters: [path("id"), idempotency],
  },
  {
    method: "post",
    path: "/api/v1/invoices/:id/transitions",
    operationId: "transitionInvoice",
    summary: "Create the message equivalent of an invoice transition",
    tag: "invoice-messages",
    responseStatus: 201,
    responseSchema: "InvoiceCommandEnvelope",
    requestSchema: "InvoiceTransitionInput",
    requestRequired: true,
    parameters: [path("id"), idempotency],
  },
  {
    method: "get",
    path: "/api/v1/invoices/:id/payments",
    operationId: "listInvoicePayments",
    summary: "List effective invoice payments",
    tag: "invoice-payments",
    responseStatus: 200,
    responseSchema: "InvoicePaymentListEnvelope",
    parameters: [path("id")],
  },
  {
    method: "post",
    path: "/api/v1/invoices/:id/payments",
    operationId: "recordInvoicePayment",
    summary: "Record a retry-safe manual invoice payment",
    tag: "invoice-payments",
    responseStatus: 201,
    responseSchema: "InvoiceCommandEnvelope",
    requestSchema: "InvoicePaymentInput",
    requestRequired: true,
    parameters: [path("id"), idempotency],
  },
  ...(["patch", "delete"] as const).map((method) => ({
    method,
    path: "/api/v1/invoices/:id/payments/:paymentId",
    operationId: `${method === "patch" ? "update" : "delete"}InvoicePayment`,
    summary: `${method === "patch" ? "Correct" : "Delete"} a retry-safe manual payment`,
    tag: "invoice-payments",
    responseStatus: 200,
    responseSchema: "InvoiceCommandEnvelope",
    requestSchema:
      method === "patch"
        ? "InvoicePaymentUpdateInput"
        : "VersionedRowDeleteInput",
    requestRequired: true,
    parameters: [path("id"), path("paymentId"), idempotency],
  })),
  {
    method: "get",
    path: "/api/v1/retainers",
    operationId: "listRetainers",
    summary: "List retainers with live balances",
    tag: "retainers",
    responseStatus: 200,
    responseSchema: "RetainerPage",
    parameters: pageParameters,
  },
  {
    method: "post",
    path: "/api/v1/retainers",
    operationId: "createRetainer",
    summary: "Create a single-denomination retainer",
    tag: "retainers",
    responseStatus: 201,
    responseSchema: "RetainerEnvelope",
    requestSchema: "RetainerInput",
    requestRequired: true,
  },
  ...(["get", "patch"] as const).map((method) => ({
    method,
    path: "/api/v1/retainers/:id",
    operationId: `${method === "get" ? "get" : "update"}Retainer`,
    summary: `${method === "get" ? "Get" : "Update"} a retainer`,
    tag: "retainers",
    responseStatus: 200,
    responseSchema: "RetainerEnvelope",
    ...(method === "patch"
      ? { requestSchema: "RetainerPatch", requestRequired: true }
      : {}),
    parameters: [path("id")],
  })),
  {
    method: "get",
    path: "/api/v1/retainers/:id/ledger",
    operationId: "listRetainerLedger",
    summary: "List append-only retainer movements",
    tag: "retainers",
    responseStatus: 200,
    responseSchema: "RetainerLedgerListEnvelope",
    parameters: [path("id")],
  },
  {
    method: "post",
    path: "/api/v1/retainers/:id/ledger",
    operationId: "appendRetainerLedger",
    summary: "Append a stable retainer movement",
    tag: "retainers",
    responseStatus: 201,
    responseSchema: "RetainerLedgerMutationEnvelope",
    requestSchema: "RetainerLedgerInput",
    requestRequired: true,
    parameters: [path("id"), idempotency],
  },
  {
    method: "post",
    path: "/api/v1/retainers/:id/drawdowns",
    operationId: "drawDownRetainer",
    summary: "Draw down a retainer and return its new balance",
    tag: "retainers",
    responseStatus: 201,
    responseSchema: "RetainerLedgerMutationEnvelope",
    requestSchema: "RetainerDrawdownInput",
    requestRequired: true,
    parameters: [path("id"), idempotency],
  },
  {
    method: "get",
    path: "/api/v1/recurring-invoices",
    operationId: "listRecurringInvoices",
    summary: "List recurring invoice definitions",
    tag: "recurring-invoices",
    responseStatus: 200,
    responseSchema: "RecurringInvoicePage",
    parameters: pageParameters,
  },
  {
    method: "post",
    path: "/api/v1/recurring-invoices",
    operationId: "createRecurringInvoice",
    summary: "Create a recurring invoice definition",
    tag: "recurring-invoices",
    responseStatus: 201,
    responseSchema: "RecurringInvoiceEnvelope",
    requestSchema: "RecurringInvoiceInput",
    requestRequired: true,
  },
  ...(["get", "patch", "delete"] as const).map((method) => ({
    method,
    path: "/api/v1/recurring-invoices/:id",
    operationId: `${method === "get" ? "get" : method === "patch" ? "update" : "delete"}RecurringInvoice`,
    summary: `${method === "get" ? "Get" : method === "patch" ? "Replace" : "Delete"} a recurring invoice definition`,
    tag: "recurring-invoices",
    responseStatus: method === "delete" ? 204 : 200,
    ...(method === "delete"
      ? {}
      : { responseSchema: "RecurringInvoiceEnvelope" }),
    ...(method === "patch"
      ? { requestSchema: "RecurringInvoiceInput", requestRequired: true }
      : {}),
    parameters: [path("id")],
  })),
];

const requiredReportRange = [
  { ...query("from", dateSchema), required: true },
  { ...query("to", dateSchema), required: true },
] as const;

const reportOperations: ApiContractOperation[] = [
  {
    method: "get",
    path: "/api/v1/reports/uninvoiced",
    operationId: "getUninvoicedReport",
    summary: "Report uninvoiced tracked time and expenses",
    tag: "reports",
    responseStatus: 200,
    responseSchema: "UninvoicedReportEnvelope",
    parameters: [
      ...requiredReportRange,
      query("client_id", integerSchema),
      query("project_id", integerSchema),
    ],
  },
  {
    method: "get",
    path: "/api/v1/reports/client-rollups/:clientId",
    operationId: "getClientRollupReport",
    summary: "Roll up reporting metrics through a client subtree",
    tag: "reports",
    responseStatus: 200,
    responseSchema: "ClientRollupReportEnvelope",
    parameters: [path("clientId"), ...requiredReportRange],
  },
  {
    method: "get",
    path: "/api/v1/reports/project-budget/:projectId",
    operationId: "getProjectBudgetReport",
    summary: "Report project budget consumption",
    tag: "reports",
    responseStatus: 200,
    responseSchema: "ProjectBudgetReportEnvelope",
    parameters: [path("projectId"), ...requiredReportRange],
  },
];

export const apiContractOperations: readonly ApiContractOperation[] = [
  {
    method: "get",
    path: "/auth/oidc/:provider",
    operationId: "startOidcSignIn",
    summary: "Start an OpenID Connect sign-in",
    tag: "authentication",
    responseStatus: 302,
    public: true,
    parameters: [stringPath("provider")],
    generateClient: false,
  },
  {
    method: "get",
    path: "/auth/oidc/:provider/callback",
    operationId: "completeOidcSignIn",
    summary: "Complete an OpenID Connect sign-in",
    tag: "authentication",
    responseStatus: 303,
    public: true,
    parameters: [stringPath("provider"), query("code"), query("state")],
    generateClient: false,
  },
  {
    method: "post",
    path: "/auth/signup",
    operationId: "signup",
    summary: "Create the first owner and send email verification",
    tag: "authentication",
    responseStatus: 202,
    responseSchema: "AuthAcceptedEnvelope",
    requestSchema: "SignupInput",
    requestRequired: true,
    public: true,
  },
  {
    method: "post",
    path: "/auth/verify-email",
    operationId: "verifyEmail",
    summary: "Verify an email address",
    tag: "authentication",
    responseStatus: 200,
    responseSchema: "AuthPrincipalEnvelope",
    requestSchema: "AuthTokenInput",
    requestRequired: true,
    public: true,
  },
  {
    method: "post",
    path: "/auth/sign-in",
    operationId: "signIn",
    summary: "Authenticate a verified email and password",
    tag: "authentication",
    responseStatus: 200,
    responseSchema: "AuthPrincipalEnvelope",
    requestSchema: "PasswordSignInInput",
    requestRequired: true,
    public: true,
  },
  {
    method: "post",
    path: "/auth/password/forgot",
    operationId: "requestPasswordReset",
    summary: "Request a password-reset email",
    tag: "authentication",
    responseStatus: 202,
    responseSchema: "AuthAcceptedEnvelope",
    requestSchema: "EmailInput",
    requestRequired: true,
    public: true,
  },
  {
    method: "post",
    path: "/auth/password/reset",
    operationId: "resetPassword",
    summary: "Consume a password-reset token",
    tag: "authentication",
    responseStatus: 200,
    responseSchema: "AuthPrincipalEnvelope",
    requestSchema: "PasswordResetInput",
    requestRequired: true,
    public: true,
  },
  {
    method: "get",
    path: "/api/v1/sessions",
    operationId: "listSessions",
    summary: "List sessions for the acting user",
    tag: "authentication",
    responseStatus: 200,
    responseSchema: "SessionPage",
    sessionOnly: true,
  },
  {
    method: "get",
    path: "/api/v1/email-log",
    operationId: "listEmailLog",
    summary: "List outbound email delivery outcomes",
    tag: "email",
    responseStatus: 200,
    responseSchema: "EmailLogPage",
    sessionOnly: true,
    parameters: [
      query("status", {
        type: "string",
        enum: ["queued", "sent", "bounced", "complained", "failed"],
      }),
      query("per_page", { type: "integer", minimum: 1, maximum: 200 }),
    ],
  },
  {
    method: "delete",
    path: "/api/v1/sessions/:sessionId",
    operationId: "revokeSession",
    summary: "Revoke a session for the acting user",
    tag: "authentication",
    responseStatus: 200,
    responseSchema: "SessionEnvelope",
    sessionOnly: true,
    parameters: [path("sessionId")],
  },
  {
    method: "get",
    path: "/api/v1",
    operationId: "getApiRoot",
    summary: "Get API service metadata",
    tag: "service",
    responseStatus: 200,
    responseSchema: "ServiceEnvelope",
  },
  {
    method: "get",
    path: "/api/v1/whoami",
    operationId: "getWhoami",
    summary: "Get the authenticated user and credential authority",
    tag: "identity",
    responseStatus: 200,
    responseSchema: "WhoamiEnvelope",
  },
  {
    method: "get",
    path: "/api/v1/api-tokens",
    operationId: "listApiTokens",
    summary: "List API tokens for the acting user",
    tag: "api-tokens",
    responseStatus: 200,
    responseSchema: "ApiTokenListEnvelope",
    sessionOnly: true,
  },
  {
    method: "post",
    path: "/api/v1/api-tokens",
    operationId: "createApiToken",
    summary: "Issue an API token",
    tag: "api-tokens",
    responseStatus: 201,
    responseSchema: "IssuedApiTokenEnvelope",
    requestSchema: "CreateApiTokenInput",
    requestRequired: true,
    sessionOnly: true,
  },
  {
    method: "delete",
    path: "/api/v1/api-tokens/:tokenId",
    operationId: "revokeApiToken",
    summary: "Revoke an API token",
    tag: "api-tokens",
    responseStatus: 200,
    responseSchema: "ApiTokenEnvelope",
    parameters: [path("tokenId")],
    sessionOnly: true,
  },
  ...generalOperations(),
  ...rateOperations(),
  ...timeEntryOperations,
  ...expenseOperations,
  ...moneyOperations,
  ...attachmentContractOperations,
  ...reportOperations,
];

const nullable = (schema: JsonSchema): JsonSchema => ({
  anyOf: [schema, { type: "null" }],
});
const reference = (name: string): JsonSchema => ({
  $ref: `#/components/schemas/${name}`,
});
const envelope = (name: string): JsonSchema => ({
  type: "object",
  required: ["data", "links"],
  properties: {
    data: reference(name),
    links: reference("Links"),
  },
  additionalProperties: false,
});
const page = (name: string): JsonSchema => ({
  type: "object",
  required: ["data", "links", "page"],
  properties: {
    data: { type: "array", items: reference(name) },
    links: reference("PageLinks"),
    page: reference("PageMetadata"),
  },
  additionalProperties: false,
});

const apiScopes = [
  "time_entries:read",
  "time_entries:write",
  "projects:read",
  "projects:write",
  "clients:read",
  "clients:write",
  "invoices:read",
  "invoices:write",
  "expenses:read",
  "expenses:write",
  "team:read",
  "schedule:read",
  "schedule:write",
  "reports:read",
] as const;

export const apiContractSchemas: Readonly<Record<string, JsonSchema>> = {
  ...attachmentContractSchemas,
  FieldError: {
    type: "object",
    required: ["field", "code", "message"],
    properties: {
      field: stringSchema,
      code: stringSchema,
      message: stringSchema,
    },
    additionalProperties: false,
  },
  ErrorDetail: {
    type: "object",
    required: ["code", "message", "fields"],
    properties: {
      code: stringSchema,
      message: stringSchema,
      fields: { type: "array", items: reference("FieldError") },
    },
    additionalProperties: false,
  },
  ErrorEnvelope: {
    type: "object",
    required: ["error", "request_id"],
    properties: {
      error: reference("ErrorDetail"),
      request_id: stringSchema,
    },
    additionalProperties: false,
  },
  SignupInput: {
    type: "object",
    required: [
      "organization_name",
      "first_name",
      "last_name",
      "email",
      "password",
    ],
    properties: {
      organization_name: stringSchema,
      first_name: stringSchema,
      last_name: stringSchema,
      email: { type: "string", format: "email" },
      password: stringSchema,
    },
    additionalProperties: false,
  },
  AuthTokenInput: {
    type: "object",
    required: ["token"],
    properties: { token: stringSchema },
    additionalProperties: false,
  },
  PasswordSignInInput: {
    type: "object",
    required: ["email", "password"],
    properties: {
      email: { type: "string", format: "email" },
      password: stringSchema,
    },
    additionalProperties: false,
  },
  EmailInput: {
    type: "object",
    required: ["email"],
    properties: { email: { type: "string", format: "email" } },
    additionalProperties: false,
  },
  PasswordResetInput: {
    type: "object",
    required: ["token", "password"],
    properties: { token: stringSchema, password: stringSchema },
    additionalProperties: false,
  },
  AuthAccepted: {
    type: "object",
    required: ["status"],
    properties: {
      status: {
        type: "string",
        enum: ["verification_sent", "reset_requested"],
      },
    },
    additionalProperties: false,
  },
  AuthAcceptedEnvelope: {
    type: "object",
    required: ["data"],
    properties: { data: reference("AuthAccepted") },
    additionalProperties: false,
  },
  AuthPrincipal: {
    type: "object",
    required: ["status", "user_id", "profile", "manager_grants"],
    properties: {
      status: {
        type: "string",
        enum: ["verified", "authenticated", "password_reset"],
      },
      user_id: integerSchema,
      profile: {
        type: "string",
        enum: [
          "member",
          "project_manager",
          "people_admin",
          "accounting",
          "executive_manager",
          "administrator",
        ],
      },
      manager_grants: { type: "array", items: stringSchema },
    },
    additionalProperties: false,
  },
  AuthPrincipalEnvelope: {
    type: "object",
    required: ["data"],
    properties: { data: reference("AuthPrincipal") },
    additionalProperties: false,
  },
  Session: {
    type: "object",
    required: [
      "id",
      "created_at",
      "last_seen_at",
      "idle_expires_at",
      "absolute_expires_at",
      "revoked_at",
      "revocation_reason",
      "current",
    ],
    properties: {
      id: integerSchema,
      created_at: timestampSchema,
      last_seen_at: timestampSchema,
      idle_expires_at: timestampSchema,
      absolute_expires_at: timestampSchema,
      revoked_at: nullable(timestampSchema),
      revocation_reason: nullable({
        type: "string",
        enum: [
          "user_revoked",
          "privilege_change",
          "password_reset",
          "user_disabled",
        ],
      }),
      current: booleanSchema,
    },
    additionalProperties: false,
  },
  SessionEnvelope: {
    type: "object",
    required: ["data"],
    properties: { data: reference("Session") },
    additionalProperties: false,
  },
  SessionPage: {
    type: "object",
    required: ["data", "links"],
    properties: {
      data: { type: "array", items: reference("Session") },
      links: reference("Links"),
    },
    additionalProperties: false,
  },
  EmailRecipient: {
    type: "object",
    required: ["email"],
    properties: {
      email: stringSchema,
      name: stringSchema,
    },
    additionalProperties: false,
  },
  EmailLog: {
    type: "object",
    required: [
      "id",
      "to",
      "template",
      "subject",
      "provider",
      "provider_message_id",
      "provider_request_id",
      "provider_latency_ms",
      "status",
      "related_type",
      "related_id",
      "attempt_count",
      "failure_code",
      "failure_reason",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      to: { type: "array", items: reference("EmailRecipient") },
      template: stringSchema,
      subject: stringSchema,
      provider: nullable(stringSchema),
      provider_message_id: nullable(stringSchema),
      provider_request_id: nullable(stringSchema),
      provider_latency_ms: nullable({
        type: "integer",
        minimum: 0,
        maximum: 3000000,
      }),
      status: {
        type: "string",
        enum: ["queued", "sent", "bounced", "complained", "failed"],
      },
      related_type: nullable(stringSchema),
      related_id: nullable(integerSchema),
      attempt_count: { type: "integer", minimum: 0 },
      failure_code: nullable({
        type: "string",
        enum: ["queue_unavailable", "provider_timeout", "provider_rejected"],
      }),
      failure_reason: nullable(stringSchema),
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  EmailLogPage: {
    type: "object",
    required: ["data", "links"],
    properties: {
      data: { type: "array", items: reference("EmailLog") },
      links: reference("Links"),
    },
    additionalProperties: false,
  },
  Links: {
    type: "object",
    required: ["self"],
    properties: { self: stringSchema },
    additionalProperties: false,
  },
  PageLinks: {
    type: "object",
    required: ["self", "next"],
    properties: { self: stringSchema, next: nullable(stringSchema) },
    additionalProperties: false,
  },
  PageMetadata: {
    type: "object",
    required: ["per_page", "next_cursor"],
    properties: {
      per_page: { type: "integer", minimum: 1, maximum: 200 },
      next_cursor: nullable(stringSchema),
    },
    additionalProperties: false,
  },
  Service: {
    type: "object",
    required: ["service", "version"],
    properties: { service: { const: "ezacto" }, version: { const: "v1" } },
    additionalProperties: false,
  },
  ServiceEnvelope: envelope("Service"),
  TokenAuthentication: {
    type: "object",
    required: ["kind", "token_id", "scopes"],
    properties: {
      kind: { const: "token" },
      token_id: integerSchema,
      scopes: { type: "array", items: { type: "string", enum: apiScopes } },
    },
    additionalProperties: false,
  },
  SessionAuthentication: {
    type: "object",
    required: ["kind"],
    properties: { kind: { const: "session" } },
    additionalProperties: false,
  },
  Whoami: {
    type: "object",
    required: ["user_id", "profile", "manager_grants", "authentication"],
    properties: {
      user_id: integerSchema,
      profile: {
        type: "string",
        enum: [
          "member",
          "project_manager",
          "people_admin",
          "accounting",
          "executive_manager",
          "administrator",
        ],
      },
      manager_grants: { type: "array", items: stringSchema },
      authentication: {
        oneOf: [
          reference("TokenAuthentication"),
          reference("SessionAuthentication"),
        ],
      },
    },
    additionalProperties: false,
  },
  WhoamiEnvelope: envelope("Whoami"),
  GeneralResource: {
    type: "object",
    required: ["id", "created_at", "updated_at"],
    properties: {
      id: integerSchema,
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: true,
  },
  GeneralMutationInput: {
    type: "object",
    minProperties: 1,
    additionalProperties: true,
  },
  GeneralResourceEnvelope: envelope("GeneralResource"),
  GeneralResourcePage: page("GeneralResource"),
  UserRate: {
    type: "object",
    required: [
      "id",
      "user_id",
      "amount_cents",
      "start_date",
      "end_date",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      user_id: integerSchema,
      amount_cents: { type: "integer", minimum: 0 },
      start_date: nullable(dateSchema),
      end_date: nullable(dateSchema),
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  UserRateInput: {
    type: "object",
    required: ["amount_cents"],
    properties: {
      amount_cents: { type: "integer", minimum: 0 },
      start_date: nullable(dateSchema),
    },
    additionalProperties: false,
  },
  UserRateEnvelope: envelope("UserRate"),
  UserRatePage: page("UserRate"),
  ApiToken: {
    type: "object",
    required: [
      "id",
      "name",
      "scopes",
      "token_hint",
      "created_at",
      "last_used_at",
      "expires_at",
      "revoked_at",
    ],
    properties: {
      id: integerSchema,
      name: stringSchema,
      scopes: { type: "array", items: { type: "string", enum: apiScopes } },
      token_hint: stringSchema,
      created_at: timestampSchema,
      last_used_at: nullable(timestampSchema),
      expires_at: nullable(timestampSchema),
      revoked_at: nullable(timestampSchema),
    },
    additionalProperties: false,
  },
  IssuedApiToken: {
    allOf: [
      reference("ApiToken"),
      {
        type: "object",
        required: ["token"],
        properties: { token: stringSchema },
      },
    ],
  },
  CreateApiTokenInput: {
    type: "object",
    required: ["name", "scopes"],
    properties: {
      name: { type: "string", minLength: 1, maxLength: 100 },
      scopes: {
        type: "array",
        minItems: 1,
        uniqueItems: true,
        items: { type: "string", enum: apiScopes },
      },
      expires_at: nullable(timestampSchema),
    },
    additionalProperties: false,
  },
  ApiTokenEnvelope: envelope("ApiToken"),
  IssuedApiTokenEnvelope: envelope("IssuedApiToken"),
  ApiTokenListEnvelope: {
    type: "object",
    required: ["data", "links"],
    properties: {
      data: { type: "array", items: reference("ApiToken") },
      links: reference("Links"),
    },
    additionalProperties: false,
  },
  TimeEntry: {
    type: "object",
    required: [
      "id",
      "user_id",
      "project_id",
      "task_id",
      "spent_date",
      "seconds",
      "is_running",
      "billable",
      "budgeted",
      "approval_status",
      "is_billed",
      "is_locked",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      user_id: integerSchema,
      project_id: integerSchema,
      task_id: integerSchema,
      user_assignment_id: integerSchema,
      task_assignment_id: integerSchema,
      spent_date: dateSchema,
      seconds: { type: "integer", minimum: 0 },
      seconds_without_timer: { type: "integer", minimum: 0 },
      rounded_seconds: { type: "integer", minimum: 0 },
      is_running: booleanSchema,
      timer_started_at: nullable(timestampSchema),
      started_time: nullable({
        type: "string",
        pattern: "^[0-2][0-9]:[0-5][0-9]$",
      }),
      ended_time: nullable({
        type: "string",
        pattern: "^[0-2][0-9]:[0-5][0-9]$",
      }),
      notes: nullable(stringSchema),
      billable: booleanSchema,
      budgeted: booleanSchema,
      approval_status: {
        type: "string",
        enum: ["unsubmitted", "submitted", "approved"],
      },
      invoice_id: nullable(integerSchema),
      is_billed: booleanSchema,
      is_locked: booleanSchema,
      locked_reason_code: nullable(stringSchema),
      locked_reason: nullable(stringSchema),
      external_ref: nullable({ type: "object", additionalProperties: true }),
      calendar_event_ref: nullable({
        type: "object",
        additionalProperties: true,
      }),
      billable_rate_cents: nullable({ type: "integer", minimum: 0 }),
      cost_rate_cents: nullable({ type: "integer", minimum: 0 }),
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  TimeEntryInput: {
    type: "object",
    required: ["project_id", "task_id"],
    properties: {
      project_id: integerSchema,
      task_id: integerSchema,
      spent_date: dateSchema,
      seconds: { type: "integer", minimum: 0 },
      started_time: { type: "string" },
      ended_time: { type: "string" },
      notes: nullable(stringSchema),
      budgeted: booleanSchema,
      external_ref: nullable({ type: "object", additionalProperties: true }),
      calendar_event_ref: nullable({
        type: "object",
        additionalProperties: true,
      }),
    },
    additionalProperties: false,
  },
  TimeEntryPatch: {
    type: "object",
    minProperties: 1,
    properties: {
      project_id: integerSchema,
      task_id: integerSchema,
      spent_date: dateSchema,
      seconds: { type: "integer", minimum: 0 },
      started_time: { type: "string" },
      ended_time: { type: "string" },
      notes: nullable(stringSchema),
      budgeted: booleanSchema,
      external_ref: nullable({ type: "object", additionalProperties: true }),
      calendar_event_ref: nullable({
        type: "object",
        additionalProperties: true,
      }),
    },
    additionalProperties: false,
  },
  TimeEntryEnvelope: envelope("TimeEntry"),
  TimeEntryPage: page("TimeEntry"),
  Expense: {
    type: "object",
    required: [
      "id",
      "user_id",
      "project_id",
      "expense_category_id",
      "spent_date",
      "total_cost_cents",
      "billable",
      "approval_status",
      "is_billed",
      "is_locked",
      "reimbursable",
      "reimbursement_status",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      user_id: integerSchema,
      project_id: integerSchema,
      expense_category_id: integerSchema,
      spent_date: dateSchema,
      notes: nullable(stringSchema),
      units: nullable({ type: "number", minimum: 0 }),
      total_cost_cents: { type: "integer", minimum: 0 },
      billable: booleanSchema,
      approval_status: {
        type: "string",
        enum: ["unsubmitted", "submitted", "approved"],
      },
      invoice_id: nullable(integerSchema),
      is_billed: booleanSchema,
      is_locked: booleanSchema,
      locked_reason_code: nullable(stringSchema),
      locked_reason: nullable(stringSchema),
      reimbursable: booleanSchema,
      reimbursement_status: {
        type: "string",
        enum: ["none", "pending", "approved", "paid"],
      },
      payout_ref: nullable(stringSchema),
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  ExpenseInput: {
    type: "object",
    required: ["project_id", "expense_category_id", "spent_date"],
    properties: {
      project_id: integerSchema,
      expense_category_id: integerSchema,
      spent_date: dateSchema,
      notes: nullable(stringSchema),
      units: { type: "number", minimum: 0 },
      total_cost_cents: { type: "integer", minimum: 0 },
      billable: booleanSchema,
      reimbursable: booleanSchema,
    },
    additionalProperties: false,
  },
  ExpensePatch: {
    type: "object",
    minProperties: 1,
    properties: {
      project_id: integerSchema,
      expense_category_id: integerSchema,
      spent_date: dateSchema,
      notes: nullable(stringSchema),
      units: { type: "number", minimum: 0 },
      total_cost_cents: { type: "integer", minimum: 0 },
      billable: booleanSchema,
      reimbursable: booleanSchema,
    },
    additionalProperties: false,
  },
  ExpenseEnvelope: envelope("Expense"),
  ExpensePage: page("Expense"),
  InvoiceLine: {
    type: "object",
    required: [
      "id",
      "invoice_id",
      "position",
      "kind",
      "description",
      "quantity",
      "unit_price_cents",
      "amount_cents",
      "taxed",
      "taxed2",
      "project_id",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      invoice_id: integerSchema,
      position: { type: "integer", minimum: 0 },
      kind: stringSchema,
      description: nullable(stringSchema),
      quantity: { type: "number" },
      unit_price_cents: { type: "integer" },
      amount_cents: { type: "integer" },
      taxed: booleanSchema,
      taxed2: booleanSchema,
      project_id: nullable(integerSchema),
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  Invoice: {
    type: "object",
    required: [
      "id",
      "client_id",
      "created_by_user_id",
      "number",
      "subject",
      "purchase_order",
      "notes",
      "currency",
      "issue_date",
      "due_date",
      "payment_terms",
      "state",
      "version",
      "close_reason",
      "close_write_off_cents",
      "sent_at",
      "paid_at",
      "paid_date",
      "closed_at",
      "period_start",
      "period_end",
      "project_id",
      "retainer_id",
      "recurring_invoice_id",
      "estimate_id",
      "reminder_policy",
      "tax_rate_ppm",
      "tax2_rate_ppm",
      "discount_rate_ppm",
      "amount_cents",
      "due_amount_cents",
      "tax_amount_cents",
      "tax2_amount_cents",
      "discount_amount_cents",
      "written_off_cents",
      "payment_options",
      "reference_token",
      "created_at",
      "updated_at",
      "line_items",
    ],
    properties: {
      id: integerSchema,
      client_id: integerSchema,
      created_by_user_id: nullable(integerSchema),
      number: stringSchema,
      subject: nullable(stringSchema),
      purchase_order: nullable(stringSchema),
      notes: nullable(stringSchema),
      currency: { type: "string", pattern: "^[A-Z]{3}$" },
      issue_date: dateSchema,
      due_date: dateSchema,
      payment_terms: {
        type: "string",
        enum: [
          "upon_receipt",
          "net_15",
          "net_30",
          "net_45",
          "net_60",
          "custom",
        ],
      },
      state: { type: "string", enum: ["draft", "open", "paid", "closed"] },
      version: { type: "integer", minimum: 0 },
      close_reason: nullable({
        type: "string",
        enum: ["cancelled", "written_off", "source_closed"],
      }),
      close_write_off_cents: { type: "integer", minimum: 0 },
      sent_at: nullable(timestampSchema),
      paid_at: nullable(timestampSchema),
      paid_date: nullable(dateSchema),
      closed_at: nullable(timestampSchema),
      period_start: nullable(dateSchema),
      period_end: nullable(dateSchema),
      project_id: nullable(integerSchema),
      retainer_id: nullable(integerSchema),
      recurring_invoice_id: nullable(integerSchema),
      estimate_id: nullable(integerSchema),
      reminder_policy: nullable({ type: "object", additionalProperties: true }),
      tax_rate_ppm: nullable({
        type: "integer",
        minimum: 0,
        maximum: 1_000_000,
      }),
      tax2_rate_ppm: nullable({
        type: "integer",
        minimum: 0,
        maximum: 1_000_000,
      }),
      discount_rate_ppm: nullable({
        type: "integer",
        minimum: 0,
        maximum: 1_000_000,
      }),
      amount_cents: { type: "integer" },
      due_amount_cents: { type: "integer", minimum: 0 },
      tax_amount_cents: { type: "integer" },
      tax2_amount_cents: { type: "integer" },
      discount_amount_cents: { type: "integer" },
      written_off_cents: { type: "integer", minimum: 0 },
      payment_options: {
        type: "array",
        uniqueItems: true,
        items: {
          type: "string",
          enum: [
            "stripe_checkout",
            "paypal_checkout",
            "quickbooks_checkout",
            "mercury_transfer",
            "wise_transfer",
          ],
        },
      },
      reference_token: nullable(stringSchema),
      created_at: timestampSchema,
      updated_at: timestampSchema,
      line_items: { type: "array", items: reference("InvoiceLine") },
    },
    additionalProperties: false,
  },
  InvoiceEnvelope: envelope("Invoice"),
  InvoicePage: page("Invoice"),
  EstimateLine: {
    type: "object",
    required: [
      "id",
      "estimate_id",
      "position",
      "kind",
      "description",
      "quantity",
      "unit_price_cents",
      "amount_cents",
      "taxed",
      "taxed2",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      estimate_id: integerSchema,
      position: { type: "integer", minimum: 0 },
      kind: stringSchema,
      description: nullable(stringSchema),
      quantity: { type: "number" },
      unit_price_cents: { type: "integer" },
      amount_cents: { type: "integer" },
      taxed: booleanSchema,
      taxed2: booleanSchema,
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  Estimate: {
    type: "object",
    required: [
      "id",
      "client_id",
      "created_by_user_id",
      "number",
      "purchase_order",
      "subject",
      "notes",
      "currency",
      "state",
      "version",
      "issue_date",
      "sent_at",
      "accepted_at",
      "declined_at",
      "tax_rate_ppm",
      "tax2_rate_ppm",
      "discount_rate_ppm",
      "amount_cents",
      "tax_amount_cents",
      "tax2_amount_cents",
      "discount_amount_cents",
      "created_at",
      "updated_at",
      "line_items",
    ],
    properties: {
      id: integerSchema,
      client_id: integerSchema,
      created_by_user_id: nullable(integerSchema),
      number: stringSchema,
      purchase_order: nullable(stringSchema),
      subject: nullable(stringSchema),
      notes: nullable(stringSchema),
      currency: { type: "string", pattern: "^[A-Z]{3}$" },
      state: {
        type: "string",
        enum: ["draft", "sent", "accepted", "declined"],
      },
      version: { type: "integer", minimum: 0 },
      issue_date: dateSchema,
      sent_at: nullable(timestampSchema),
      accepted_at: nullable(timestampSchema),
      declined_at: nullable(timestampSchema),
      tax_rate_ppm: nullable({
        type: "integer",
        minimum: 0,
        maximum: 1_000_000,
      }),
      tax2_rate_ppm: nullable({
        type: "integer",
        minimum: 0,
        maximum: 1_000_000,
      }),
      discount_rate_ppm: nullable({
        type: "integer",
        minimum: 0,
        maximum: 1_000_000,
      }),
      amount_cents: { type: "integer" },
      tax_amount_cents: { type: "integer" },
      tax2_amount_cents: { type: "integer" },
      discount_amount_cents: { type: "integer" },
      created_at: timestampSchema,
      updated_at: timestampSchema,
      line_items: { type: "array", items: reference("EstimateLine") },
    },
    additionalProperties: false,
  },
  EstimateEnvelope: envelope("Estimate"),
  EstimatePage: page("Estimate"),
  EstimateMessage: {
    type: "object",
    required: [
      "id",
      "estimate_id",
      "sent_by",
      "sent_by_email",
      "sent_from",
      "sent_from_email",
      "recipients",
      "subject",
      "body",
      "send_me_a_copy",
      "event_type",
      "delivery_status",
      "provider_message_id",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      estimate_id: integerSchema,
      sent_by: nullable(stringSchema),
      sent_by_email: nullable(stringSchema),
      sent_from: nullable(stringSchema),
      sent_from_email: nullable(stringSchema),
      recipients: { type: "array", items: reference("InvoiceRecipient") },
      subject: nullable(stringSchema),
      body: nullable(stringSchema),
      send_me_a_copy: booleanSchema,
      event_type: nullable({
        type: "string",
        enum: ["send", "accept", "decline", "re-open", "view", "invoice"],
      }),
      delivery_status: nullable({
        type: "string",
        enum: ["queued", "sent", "bounced", "complained", "failed"],
      }),
      provider_message_id: nullable(stringSchema),
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  EstimateMessageListEnvelope: {
    type: "object",
    required: ["data", "links"],
    properties: {
      data: { type: "array", items: reference("EstimateMessage") },
      links: reference("Links"),
    },
    additionalProperties: false,
  },
  EstimateMessageInput: {
    oneOf: [
      {
        type: "object",
        required: ["expected_version", "event_type", "recipients"],
        properties: {
          expected_version: { type: "integer", minimum: 0 },
          event_type: { const: "send" },
          recipients: {
            type: "array",
            minItems: 1,
            maxItems: 1_000,
            items: reference("InvoiceRecipient"),
          },
          subject: nullable(stringSchema),
          body: nullable(stringSchema),
          send_me_a_copy: booleanSchema,
        },
        additionalProperties: false,
      },
      {
        type: "object",
        required: ["expected_version", "event_type"],
        properties: {
          expected_version: { type: "integer", minimum: 0 },
          event_type: {
            type: "string",
            enum: ["accept", "decline", "re-open"],
          },
          recipients: {
            type: "array",
            maxItems: 1_000,
            items: reference("InvoiceRecipient"),
          },
          subject: nullable(stringSchema),
          body: nullable(stringSchema),
          send_me_a_copy: booleanSchema,
        },
        additionalProperties: false,
      },
    ],
  },
  EstimateMessageCommandResponse: {
    type: "object",
    required: ["estimate", "message"],
    properties: {
      estimate: reference("Estimate"),
      message: reference("EstimateMessage"),
    },
    additionalProperties: false,
  },
  EstimateMessageCommandEnvelope: envelope("EstimateMessageCommandResponse"),
  EstimateConversionInput: {
    type: "object",
    required: [
      "expected_version",
      "number",
      "issue_date",
      "due_date",
      "payment_terms",
    ],
    properties: {
      expected_version: { type: "integer", minimum: 0 },
      number: { type: "string", minLength: 1, maxLength: 255 },
      issue_date: dateSchema,
      due_date: dateSchema,
      payment_terms: {
        type: "string",
        enum: [
          "upon_receipt",
          "net_15",
          "net_30",
          "net_45",
          "net_60",
          "custom",
        ],
      },
    },
    additionalProperties: false,
  },
  EstimateConversion: {
    type: "object",
    required: ["invoice", "event"],
    properties: {
      invoice: reference("Invoice"),
      event: reference("EstimateMessage"),
    },
    additionalProperties: false,
  },
  EstimateConversionEnvelope: envelope("EstimateConversion"),
  InvoiceGenerationInput: {
    type: "object",
    required: [
      "client_id",
      "from",
      "to",
      "project_ids",
      "time_summary_type",
      "expense_summary_type",
    ],
    properties: {
      client_id: integerSchema,
      from: dateSchema,
      to: dateSchema,
      project_ids: {
        type: "array",
        minItems: 1,
        maxItems: 10_000,
        uniqueItems: true,
        items: integerSchema,
      },
      time_summary_type: nullable({
        type: "string",
        enum: ["project", "task", "people", "detailed"],
      }),
      expense_summary_type: nullable({
        type: "string",
        enum: ["project", "category", "people", "detailed"],
      }),
    },
    additionalProperties: false,
  },
  InvoiceCommandSnapshot: {
    type: "object",
    required: [
      "id",
      "version",
      "updated_at",
      "state",
      "close_reason",
      "close_write_off_cents",
      "sent_at",
      "paid_at",
      "paid_date",
      "closed_at",
      "amount_cents",
      "due_amount_cents",
      "written_off_cents",
      "payment_count",
      "payment_status",
    ],
    properties: {
      id: integerSchema,
      version: { type: "integer", minimum: 0 },
      updated_at: timestampSchema,
      state: { type: "string", enum: ["draft", "open", "paid", "closed"] },
      close_reason: nullable({
        type: "string",
        enum: ["cancelled", "written_off", "source_closed"],
      }),
      close_write_off_cents: { type: "integer", minimum: 0 },
      sent_at: nullable(timestampSchema),
      paid_at: nullable(timestampSchema),
      paid_date: nullable(dateSchema),
      closed_at: nullable(timestampSchema),
      amount_cents: { type: "integer" },
      due_amount_cents: { type: "integer", minimum: 0 },
      written_off_cents: { type: "integer", minimum: 0 },
      payment_count: { type: "integer", minimum: 0 },
      payment_status: { type: "string", enum: ["unpaid", "partial", "paid"] },
    },
    additionalProperties: false,
  },
  InvoiceCommandResult: {
    type: "object",
    required: [
      "schema_version",
      "event_ids",
      "first_aggregate_sequence",
      "event_count",
      "invoice",
    ],
    properties: {
      schema_version: { const: 1 },
      event_ids: {
        type: "array",
        minItems: 1,
        maxItems: 2,
        items: stringSchema,
      },
      first_aggregate_sequence: { type: "integer", minimum: 1 },
      event_count: { type: "integer", minimum: 1, maximum: 2 },
      invoice: reference("InvoiceCommandSnapshot"),
    },
    additionalProperties: false,
  },
  InvoiceCommandResponse: {
    type: "object",
    required: ["invoice", "command"],
    properties: {
      invoice: reference("Invoice"),
      command: reference("InvoiceCommandResult"),
    },
    additionalProperties: false,
  },
  InvoiceCommandEnvelope: envelope("InvoiceCommandResponse"),
  InvoiceEditInput: {
    type: "object",
    required: ["expected_version"],
    minProperties: 2,
    properties: {
      expected_version: { type: "integer", minimum: 0 },
      client_id: integerSchema,
      number: { type: "string", minLength: 1, maxLength: 255 },
      subject: nullable(stringSchema),
      purchase_order: nullable(stringSchema),
      notes: nullable(stringSchema),
      currency: { type: "string", pattern: "^[A-Z]{3}$" },
      issue_date: dateSchema,
      due_date: dateSchema,
      payment_terms: {
        type: "string",
        enum: [
          "upon_receipt",
          "net_15",
          "net_30",
          "net_45",
          "net_60",
          "custom",
        ],
      },
      project_id: nullable(integerSchema),
      reminder_policy: nullable({ type: "object", additionalProperties: true }),
      payment_options: {
        type: "array",
        uniqueItems: true,
        items: {
          type: "string",
          enum: [
            "stripe_checkout",
            "paypal_checkout",
            "quickbooks_checkout",
            "mercury_transfer",
            "wise_transfer",
          ],
        },
      },
      tax_rate_ppm: nullable({
        type: "integer",
        minimum: 0,
        maximum: 1_000_000,
      }),
      tax2_rate_ppm: nullable({
        type: "integer",
        minimum: 0,
        maximum: 1_000_000,
      }),
      discount_rate_ppm: nullable({
        type: "integer",
        minimum: 0,
        maximum: 1_000_000,
      }),
    },
    additionalProperties: false,
  },
  InvoiceLineInput: {
    type: "object",
    required: [
      "expected_version",
      "position",
      "kind",
      "quantity",
      "unit_price_cents",
    ],
    properties: {
      expected_version: { type: "integer", minimum: 0 },
      position: { type: "integer", minimum: 0 },
      kind: { type: "string", minLength: 1, maxLength: 255 },
      description: nullable(stringSchema),
      quantity: { type: "number" },
      unit_price_cents: {
        type: "integer",
        minimum: -9_000_000_000_000,
        maximum: 9_000_000_000_000,
      },
      taxed: booleanSchema,
      taxed2: booleanSchema,
      project_id: nullable(integerSchema),
    },
    additionalProperties: false,
  },
  InvoiceLineUpdateInput: {
    type: "object",
    required: [
      "expected_version",
      "expected_updated_at",
      "position",
      "kind",
      "quantity",
      "unit_price_cents",
    ],
    properties: {
      expected_version: { type: "integer", minimum: 0 },
      expected_updated_at: timestampSchema,
      position: { type: "integer", minimum: 0 },
      kind: { type: "string", minLength: 1, maxLength: 255 },
      description: nullable(stringSchema),
      quantity: { type: "number" },
      unit_price_cents: {
        type: "integer",
        minimum: -9_000_000_000_000,
        maximum: 9_000_000_000_000,
      },
      taxed: booleanSchema,
      taxed2: booleanSchema,
      project_id: nullable(integerSchema),
    },
    additionalProperties: false,
  },
  VersionedRowDeleteInput: {
    type: "object",
    required: ["expected_version", "expected_updated_at"],
    properties: {
      expected_version: { type: "integer", minimum: 0 },
      expected_updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  InvoiceRecipient: {
    type: "object",
    required: ["name", "email"],
    properties: {
      name: { type: "string", maxLength: 1_000 },
      email: { type: "string", minLength: 3, maxLength: 320 },
    },
    additionalProperties: false,
  },
  InvoiceMessage: {
    type: "object",
    required: [
      "id",
      "invoice_id",
      "sent_by",
      "sent_by_email",
      "sent_from",
      "sent_from_email",
      "recipients",
      "subject",
      "body",
      "attach_pdf",
      "send_me_a_copy",
      "thank_you",
      "reminder",
      "send_reminder_on",
      "event_type",
      "delivery_status",
      "provider_message_id",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      invoice_id: integerSchema,
      sent_by: nullable(stringSchema),
      sent_by_email: nullable(stringSchema),
      sent_from: nullable(stringSchema),
      sent_from_email: nullable(stringSchema),
      recipients: { type: "array", items: reference("InvoiceRecipient") },
      subject: nullable(stringSchema),
      body: nullable(stringSchema),
      attach_pdf: booleanSchema,
      send_me_a_copy: booleanSchema,
      thank_you: booleanSchema,
      reminder: booleanSchema,
      send_reminder_on: nullable(dateSchema),
      event_type: nullable(stringSchema),
      delivery_status: nullable(stringSchema),
      provider_message_id: nullable(stringSchema),
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  InvoiceMessageListEnvelope: {
    type: "object",
    required: ["data", "links"],
    properties: {
      data: { type: "array", items: reference("InvoiceMessage") },
      links: reference("Links"),
    },
    additionalProperties: false,
  },
  InvoiceMessageInput: {
    type: "object",
    required: ["event_type", "expected_version"],
    properties: {
      event_type: {
        type: "string",
        enum: ["send", "draft", "cancel", "write_off", "reopen", "re-open"],
      },
      expected_version: { type: "integer", minimum: 0 },
      recipients: {
        type: "array",
        maxItems: 1_000,
        items: reference("InvoiceRecipient"),
      },
      subject: nullable(stringSchema),
      body: nullable(stringSchema),
      attach_pdf: booleanSchema,
      send_me_a_copy: booleanSchema,
      thank_you: booleanSchema,
      reminder: booleanSchema,
      send_reminder_on: nullable(dateSchema),
    },
    additionalProperties: false,
  },
  InvoiceTransitionInput: {
    type: "object",
    required: ["command", "expected_version"],
    properties: {
      command: {
        type: "string",
        enum: ["send", "draft", "cancel", "write_off", "reopen", "re-open"],
      },
      expected_version: { type: "integer", minimum: 0 },
      recipients: {
        type: "array",
        maxItems: 1_000,
        items: reference("InvoiceRecipient"),
      },
      subject: nullable(stringSchema),
      body: nullable(stringSchema),
      attach_pdf: booleanSchema,
      send_me_a_copy: booleanSchema,
      thank_you: booleanSchema,
      reminder: booleanSchema,
      send_reminder_on: nullable(dateSchema),
    },
    additionalProperties: false,
  },
  InvoicePayment: {
    type: "object",
    required: [
      "id",
      "invoice_id",
      "currency",
      "amount_cents",
      "paid_at",
      "paid_date",
      "notes",
      "recorded_by_user_id",
      "provider",
      "provider_shape",
      "provider_account_id",
      "provider_transaction_id",
      "bank_deposit_id",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      invoice_id: integerSchema,
      currency: { type: "string", pattern: "^[A-Z]{3}$" },
      amount_cents: { type: "integer", minimum: 1 },
      paid_at: nullable(timestampSchema),
      paid_date: nullable(dateSchema),
      notes: nullable(stringSchema),
      recorded_by_user_id: nullable(integerSchema),
      provider: stringSchema,
      provider_shape: stringSchema,
      provider_account_id: nullable(integerSchema),
      provider_transaction_id: nullable(stringSchema),
      bank_deposit_id: nullable(integerSchema),
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  InvoicePaymentListEnvelope: {
    type: "object",
    required: ["data", "links"],
    properties: {
      data: { type: "array", items: reference("InvoicePayment") },
      links: reference("Links"),
    },
    additionalProperties: false,
  },
  InvoicePaymentInput: {
    type: "object",
    required: ["expected_version", "amount_cents", "currency"],
    properties: {
      expected_version: { type: "integer", minimum: 0 },
      amount_cents: { type: "integer", minimum: 1, maximum: 9_000_000_000_000 },
      currency: { type: "string", pattern: "^[A-Z]{3}$" },
      paid_at: nullable(timestampSchema),
      paid_date: nullable(dateSchema),
      notes: nullable(stringSchema),
    },
    additionalProperties: false,
  },
  InvoicePaymentUpdateInput: {
    type: "object",
    required: ["expected_version", "expected_updated_at", "amount_cents"],
    properties: {
      expected_version: { type: "integer", minimum: 0 },
      expected_updated_at: timestampSchema,
      amount_cents: { type: "integer", minimum: 1, maximum: 9_000_000_000_000 },
      paid_at: nullable(timestampSchema),
      paid_date: nullable(dateSchema),
      notes: nullable(stringSchema),
    },
    additionalProperties: false,
  },
  Retainer: {
    type: "object",
    required: [
      "id",
      "client_id",
      "project_id",
      "state",
      "denomination",
      "amount_cents",
      "seconds",
      "locked_rate_cents",
      "rate_locked_at",
      "period",
      "rollover",
      "expires_at",
      "on_exhaustion",
      "balance",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      client_id: nullable(integerSchema),
      project_id: nullable(integerSchema),
      state: { type: "string", enum: ["ongoing", "closed"] },
      denomination: { type: "string", enum: ["money", "hours"] },
      amount_cents: nullable({ type: "integer", minimum: 0 }),
      seconds: nullable({ type: "integer", minimum: 0 }),
      locked_rate_cents: nullable({ type: "integer", minimum: 0 }),
      rate_locked_at: nullable(timestampSchema),
      period: nullable(stringSchema),
      rollover: nullable({ type: "string", enum: ["carry", "expire", "cap"] }),
      expires_at: nullable(dateSchema),
      on_exhaustion: { type: "string", enum: ["block", "warn", "overflow"] },
      balance: { type: "integer" },
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  RetainerEnvelope: envelope("Retainer"),
  RetainerPage: page("Retainer"),
  RetainerInput: {
    type: "object",
    required: ["denomination"],
    properties: {
      client_id: nullable(integerSchema),
      project_id: nullable(integerSchema),
      denomination: { type: "string", enum: ["money", "hours"] },
      amount_cents: nullable({
        type: "integer",
        minimum: 0,
        maximum: 9_000_000_000_000,
      }),
      seconds: nullable({ type: "integer", minimum: 0 }),
      locked_rate_cents: nullable({
        type: "integer",
        minimum: 0,
        maximum: 9_000_000_000_000,
      }),
      rate_locked_at: nullable(timestampSchema),
      period: nullable({ type: "string", maxLength: 64 }),
      rollover: nullable({ type: "string", enum: ["carry", "expire", "cap"] }),
      expires_at: nullable(dateSchema),
      on_exhaustion: { type: "string", enum: ["block", "warn", "overflow"] },
    },
    additionalProperties: false,
  },
  RetainerPatch: {
    type: "object",
    minProperties: 1,
    properties: {
      state: { type: "string", enum: ["ongoing", "closed"] },
      period: nullable({ type: "string", maxLength: 64 }),
      rollover: nullable({ type: "string", enum: ["carry", "expire", "cap"] }),
      expires_at: nullable(dateSchema),
      on_exhaustion: { type: "string", enum: ["block", "warn", "overflow"] },
    },
    additionalProperties: false,
  },
  RetainerLedgerEntry: {
    type: "object",
    required: [
      "id",
      "retainer_id",
      "kind",
      "unit",
      "amount",
      "invoice_id",
      "occurred_on",
      "notes",
      "created_at",
    ],
    properties: {
      id: stringSchema,
      retainer_id: integerSchema,
      kind: {
        type: "string",
        enum: ["deposit", "drawdown", "expiry", "reset", "adjustment"],
      },
      unit: { type: "string", enum: ["cents", "seconds"] },
      amount: { type: "integer" },
      invoice_id: nullable(integerSchema),
      occurred_on: dateSchema,
      notes: nullable(stringSchema),
      created_at: timestampSchema,
    },
    additionalProperties: false,
  },
  RetainerLedgerListEnvelope: {
    type: "object",
    required: ["data", "links"],
    properties: {
      data: { type: "array", items: reference("RetainerLedgerEntry") },
      links: reference("Links"),
    },
    additionalProperties: false,
  },
  RetainerLedgerMutation: {
    type: "object",
    required: ["entry", "balance", "denomination"],
    properties: {
      entry: reference("RetainerLedgerEntry"),
      balance: { type: "integer" },
      denomination: { type: "string", enum: ["money", "hours"] },
    },
    additionalProperties: false,
  },
  RetainerLedgerMutationEnvelope: envelope("RetainerLedgerMutation"),
  RetainerLedgerInput: {
    type: "object",
    required: ["kind", "occurred_on"],
    properties: {
      kind: {
        type: "string",
        enum: ["deposit", "drawdown", "expiry", "reset", "adjustment"],
      },
      invoice_id: nullable(integerSchema),
      amount_cents: { type: "integer", minimum: 1, maximum: 9_000_000_000_000 },
      seconds: { type: "integer", minimum: 1 },
      occurred_on: dateSchema,
      notes: nullable(stringSchema),
    },
    additionalProperties: false,
  },
  RetainerDrawdownInput: {
    type: "object",
    required: ["invoice_id", "occurred_on"],
    properties: {
      invoice_id: integerSchema,
      amount_cents: { type: "integer", minimum: 1, maximum: 9_000_000_000_000 },
      seconds: { type: "integer", minimum: 1 },
      occurred_on: dateSchema,
      notes: nullable(stringSchema),
    },
    additionalProperties: false,
  },
  RecurringFixedLine: {
    type: "object",
    required: [
      "kind",
      "description",
      "quantity",
      "unit_price_cents",
      "taxed",
      "taxed2",
      "project_id",
    ],
    properties: {
      kind: stringSchema,
      description: nullable(stringSchema),
      quantity: { type: "number" },
      unit_price_cents: { type: "integer" },
      taxed: booleanSchema,
      taxed2: booleanSchema,
      project_id: nullable(integerSchema),
    },
    additionalProperties: false,
  },
  RecurringAmountConfig: {
    oneOf: [
      {
        type: "object",
        required: ["schema_version", "type", "line_items"],
        properties: {
          schema_version: { const: 1 },
          type: { const: "fixed_lines" },
          line_items: { type: "array", items: reference("RecurringFixedLine") },
        },
        additionalProperties: false,
      },
      {
        type: "object",
        required: ["schema_version", "type", "project_ids"],
        properties: {
          schema_version: { const: 1 },
          type: { const: "line_items_import" },
          project_ids: {
            type: "array",
            uniqueItems: true,
            items: integerSchema,
          },
          time: {
            type: "object",
            required: ["summary_type"],
            properties: {
              summary_type: {
                type: "string",
                enum: ["project", "task", "people", "detailed"],
              },
            },
            additionalProperties: false,
          },
          expenses: {
            type: "object",
            required: ["summary_type"],
            properties: {
              summary_type: {
                type: "string",
                enum: ["project", "category", "people", "detailed"],
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    ],
  },
  RecurringInvoice: {
    type: "object",
    required: [
      "id",
      "client_id",
      "subject_template",
      "notes_template",
      "every_n_months",
      "day_of_month",
      "next_issue_on",
      "amount_config",
      "can_draw_from_retainer_id",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: integerSchema,
      client_id: integerSchema,
      subject_template: stringSchema,
      notes_template: stringSchema,
      every_n_months: { type: "integer", minimum: 1 },
      day_of_month: { type: "integer", minimum: 1, maximum: 31 },
      next_issue_on: dateSchema,
      amount_config: reference("RecurringAmountConfig"),
      can_draw_from_retainer_id: nullable(integerSchema),
      created_at: timestampSchema,
      updated_at: timestampSchema,
    },
    additionalProperties: false,
  },
  RecurringInvoiceEnvelope: envelope("RecurringInvoice"),
  RecurringInvoicePage: page("RecurringInvoice"),
  RecurringInvoiceInput: {
    type: "object",
    required: [
      "client_id",
      "subject_template",
      "notes_template",
      "every_n_months",
      "day_of_month",
      "next_issue_on",
      "amount_config",
    ],
    properties: {
      client_id: integerSchema,
      subject_template: { type: "string", minLength: 1 },
      notes_template: stringSchema,
      every_n_months: { type: "integer", minimum: 1 },
      day_of_month: { type: "integer", minimum: 1, maximum: 31 },
      next_issue_on: dateSchema,
      amount_config: reference("RecurringAmountConfig"),
      can_draw_from_retainer_id: nullable(integerSchema),
    },
    additionalProperties: false,
  },
  UninvoicedCurrencyTotal: {
    type: "object",
    required: [
      "currency",
      "rounded_seconds",
      "time_entry_count",
      "unpriced_time_entry_count",
      "expense_count",
    ],
    properties: {
      currency: stringSchema,
      rounded_seconds: { type: "integer", minimum: 0 },
      time_entry_count: { type: "integer", minimum: 0 },
      unpriced_time_entry_count: { type: "integer", minimum: 0 },
      expense_count: { type: "integer", minimum: 0 },
      time_cents: { type: "integer", minimum: 0 },
      expense_cents: { type: "integer", minimum: 0 },
      total_cents: { type: "integer", minimum: 0 },
    },
    additionalProperties: false,
  },
  UninvoicedReport: {
    type: "object",
    required: ["from", "to", "client_id", "project_id", "totals"],
    properties: {
      from: dateSchema,
      to: dateSchema,
      client_id: nullable(integerSchema),
      project_id: nullable(integerSchema),
      totals: { type: "array", items: reference("UninvoicedCurrencyTotal") },
    },
    additionalProperties: false,
  },
  UninvoicedReportEnvelope: envelope("UninvoicedReport"),
  ClientRollupCurrency: {
    type: "object",
    required: ["currency", "expense_cents"],
    properties: {
      currency: stringSchema,
      expense_cents: { type: "integer", minimum: 0 },
      uninvoiced_time_cents: { type: "integer", minimum: 0 },
      uninvoiced_expense_cents: { type: "integer", minimum: 0 },
      uninvoiced_total_cents: { type: "integer", minimum: 0 },
      money_budget_cents: { type: "integer", minimum: 0 },
      cost_cents: { type: "integer", minimum: 0 },
    },
    additionalProperties: false,
  },
  ClientRollupMetrics: {
    type: "object",
    required: [
      "time_entry_count",
      "expense_count",
      "rounded_seconds",
      "billable_seconds",
      "budgeted_seconds",
      "time_budget_seconds",
      "unpriced_billable_entry_count",
      "unpriced_cost_entry_count",
      "currencies",
    ],
    properties: {
      time_entry_count: { type: "integer", minimum: 0 },
      expense_count: { type: "integer", minimum: 0 },
      rounded_seconds: { type: "integer", minimum: 0 },
      billable_seconds: { type: "integer", minimum: 0 },
      budgeted_seconds: { type: "integer", minimum: 0 },
      time_budget_seconds: { type: "integer", minimum: 0 },
      unpriced_billable_entry_count: { type: "integer", minimum: 0 },
      unpriced_cost_entry_count: { type: "integer", minimum: 0 },
      currencies: { type: "array", items: reference("ClientRollupCurrency") },
    },
    additionalProperties: false,
  },
  ClientRollupNode: {
    type: "object",
    required: [
      "client_id",
      "name",
      "parent_client_id",
      "depth",
      "direct",
      "rollup",
    ],
    properties: {
      client_id: integerSchema,
      name: stringSchema,
      parent_client_id: nullable(integerSchema),
      depth: { type: "integer", minimum: 0 },
      direct: reference("ClientRollupMetrics"),
      rollup: reference("ClientRollupMetrics"),
    },
    additionalProperties: false,
  },
  ClientRollupReport: {
    type: "object",
    required: ["root_client_id", "from", "to", "nodes"],
    properties: {
      root_client_id: integerSchema,
      from: dateSchema,
      to: dateSchema,
      nodes: { type: "array", items: reference("ClientRollupNode") },
    },
    additionalProperties: false,
  },
  ClientRollupReportEnvelope: envelope("ClientRollupReport"),
  ProjectBudgetGrain: {
    type: "object",
    required: [
      "source",
      "source_id",
      "unit",
      "calculation",
      "unpriced_entry_count",
    ],
    properties: {
      source: {
        type: "string",
        enum: ["project", "task_assignment", "user_assignment"],
      },
      source_id: integerSchema,
      unit: { type: "string", enum: ["seconds", "cents"] },
      calculation: { type: "string", enum: ["time", "billable", "cost"] },
      unpriced_entry_count: { type: "integer", minimum: 0 },
      budget_seconds: nullable({ type: "integer", minimum: 0 }),
      spent_seconds: { type: "integer", minimum: 0 },
      remaining_seconds: nullable({ type: "integer" }),
      budget_cents: nullable({ type: "integer", minimum: 0 }),
      spent_cents: { type: "integer", minimum: 0 },
      remaining_cents: nullable({ type: "integer" }),
    },
    additionalProperties: false,
  },
  ProjectBudgetReport: {
    type: "object",
    required: [
      "project_id",
      "budget_by",
      "expenses_included",
      "from",
      "to",
      "grains",
    ],
    properties: {
      project_id: integerSchema,
      budget_by: {
        type: "string",
        enum: [
          "project",
          "project_cost",
          "task",
          "task_fees",
          "person",
          "none",
        ],
      },
      expenses_included: booleanSchema,
      from: dateSchema,
      to: dateSchema,
      grains: { type: "array", items: reference("ProjectBudgetGrain") },
    },
    additionalProperties: false,
  },
  ProjectBudgetReportEnvelope: envelope("ProjectBudgetReport"),
};

const openApiPath = (runtimePath: string): string =>
  runtimePath.replace(/:([A-Za-z][A-Za-z0-9]*)/g, "{$1}");

const schemaResponse = (schema: string): Record<string, unknown> => ({
  description: "Successful response",
  content: {
    "application/json": { schema: reference(schema) },
  },
});

const errorResponse = (description: string): Record<string, unknown> => ({
  description,
  content: {
    "application/json": { schema: reference("ErrorEnvelope") },
  },
});

const successResponse = (
  operation: ApiContractOperation,
): Record<string, unknown> => {
  if (operation.responseStatus === 204) return { description: "No content" };
  if (operation.responseStatus >= 300 && operation.responseStatus < 400) {
    return {
      description: "Redirect response",
      headers: {
        Location: {
          description: "Redirect target",
          schema: stringSchema,
        },
      },
    };
  }
  if (operation.binaryResponse === true) {
    return {
      description: "Attachment content",
      content: {
        "application/octet-stream": {
          schema: { type: "string", format: "binary" },
        },
      },
    };
  }
  return schemaResponse(operation.responseSchema ?? "ErrorEnvelope");
};

export const generateOpenApiDocument = (): Record<string, unknown> => {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const operation of apiContractOperations) {
    const route = openApiPath(operation.path);
    const responses: Record<string, unknown> = {
      [operation.responseStatus]: successResponse(operation),
      "400": { $ref: "#/components/responses/MalformedRequest" },
      "401": { $ref: "#/components/responses/AuthenticationRequired" },
      "403": { $ref: "#/components/responses/InsufficientPermission" },
      "404": { $ref: "#/components/responses/ResourceNotFound" },
      "409": { $ref: "#/components/responses/StateConflict" },
      "413": { $ref: "#/components/responses/PayloadTooLarge" },
      "422": { $ref: "#/components/responses/ValidationFailed" },
      "429": { $ref: "#/components/responses/RateLimited" },
      "503": { $ref: "#/components/responses/ServiceUnavailable" },
    };
    const entry: Record<string, unknown> = {
      operationId: operation.operationId,
      summary: operation.summary,
      tags: [operation.tag],
      security: operation.public
        ? []
        : operation.sessionOnly
          ? [{ cookieSession: [] }]
          : [{ bearerAuth: [] }, { cookieSession: [] }],
      responses,
      "x-ezacto-runtime-path": operation.path,
      "x-ezacto-generate-client": operation.generateClient !== false,
    };
    if (operation.parameters !== undefined)
      entry.parameters = operation.parameters.map((parameter) => ({
        name: parameter.name,
        in: parameter.location,
        required: parameter.location === "path" || parameter.required === true,
        schema: parameter.schema,
      }));
    if (operation.requestSchema !== undefined) {
      entry.requestBody = {
        required: operation.requestRequired === true,
        content: {
          [operation.requestContentType ?? "application/json"]: {
            schema: reference(operation.requestSchema),
          },
        },
      };
    }
    (paths[route] ??= {})[operation.method] = entry;
  }

  return {
    openapi: "3.1.0",
    info: {
      title: "ezacto API",
      version: "1.0.0",
      description:
        "The native ezacto v1 contract. Contract and generated clients are deterministic build artifacts.",
    },
    servers: [{ url: "https://ezacto.io" }],
    paths,
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer" },
        cookieSession: {
          type: "apiKey",
          in: "cookie",
          name: "__Host-ezacto_session",
        },
      },
      responses: {
        MalformedRequest: errorResponse("Malformed request"),
        AuthenticationRequired: errorResponse("Authentication required"),
        InsufficientPermission: errorResponse("Insufficient permission"),
        ResourceNotFound: errorResponse("Resource not found"),
        StateConflict: errorResponse("State conflict"),
        PayloadTooLarge: errorResponse("Payload too large"),
        ValidationFailed: errorResponse("Validation failed"),
        RateLimited: errorResponse("Rate limited"),
        ServiceUnavailable: errorResponse("Service unavailable"),
      },
      schemas: apiContractSchemas,
    },
  };
};
